version: '3'
services:
  postgres:
    image: postgres:13
    user: "1001:1001"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - "5000"
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - postgres