

def create_PSO_job():
    CRE_PSO_JOB = {
                "DATA": [
                    {
                    "<Release Reference Label-1>": "REL-8315683480",
                    "<Release Reference Label-2>": "REL-9191904884",
                    "<Release Reference Label-3>": "REL-0303692927",
                    "<Release Reference Label-4>": "REL-3263683094",
                    "PSO_DATE": "2021-11-10T00:00:00+07:00",
                    "REL_PREFIX": 'null',
                    "TEAM": 'null',
                    "EXP_RELEASE_DATE": 'null',
                    "INVOICE_NO": 'null',
                    "TP_VEHICLE_NO": 'null',
                    "TP_BOOKING": 'null',
                    "TP_CARRIER": 'null',
                    "TP_CONTAINER_NO_1": 'null',
                    "TP_CONTAINER_TYPE_1": 'null',
                    "TP_SEAL_NO_1": 'null',
                    "TP_CONTAINER_NO_2": 'null',
                    "TP_CONTAINER_TYPE_2": 'null',
                    "TP_SEAL_NO_2": 'null',
                    "TP_CONTAINER_NO_3": 'null',
                    "TP_CONTAINER_TYPE_3": 'null',
                    "TP_SEAL_NO_3": 'null',
                    "TP_AIRWAYBILL": 'null',
                    "TP_BILL_OF_LANDING": 'null',
                    "TP_ORIGIN": 'null',
                    "TP_VESSEL": 'null',
                    "TP_PORT_OF_LANDING": 'null',
                    "TP_PORT_DISCHARGE": 'null',
                    "TP_VOYAGE": 'null',
                    "TP_ETD": 'null',
                    "CON_CODE": 'null',
                    "CON_COMPANY": 'null',
                    "CON_TAX_NO": 'null',
                    "CON_BRANCH": 'null',
                    "CON_ADDRESS": 'null',
                    "CON_ADDRESS2": 'null',
                    "CON_AREA1": 'null',
                    "CON_AREA2": 'null',
                    "CON_AREA3": 'null',
                    "CON_AREA4": 'null',
                    "CON_ZONE1": 'null',
                    "CON_ZONE2": 'null',
                    "CON_REGION1": 'null',
                    "CON_REGION2": 'null',
                    "CON_COUNTRY": 'null',
                    "CON_ZIP": 'null',
                    "CON_CONTACT_NAME": 'null',
                    "CON_CONTACT_PHONE": 'null',
                    "CON_CONTACT_EMAIL": 'null',
                    "CON_NOTE": 'null',
                    "ST_CODE": 'null',
                    "ST_COMPANY": 'null',
                    "ST_ADDRESS": 'null',
                    "ST_ADDRESS2": 'null',
                    "ST_AREA1": 'null',
                    "ST_AREA2": 'null',
                    "ST_AREA3": 'null',
                    "ST_AREA4": 'null',
                    "ST_ZONE1": 'null',
                    "ST_ZONE2": 'null',
                    "ST_REGION1": 'null',
                    "ST_REGION2": 'null',
                    "ST_COUNTRY": 'null',
                    "ST_ZIP": 'null',
                    "ST_CONTACT_NAME": 'null',
                    "ST_CONTACT_PHONE": 'null',
                    "ST_CONTACT_EMAIL": 'null',
                    "ST_NOTE": 'null',
                    "DEL_CONSIGNMENT": 'null',
                    "DEL_URGENT_ORDER": 'null',
                    "DEL_COD": 'null',
                    "DEL_COD_AMOUNT": 'null',
                    "DELIVERY_TIME_FROM": 'null',
                    "DELIVERY_TIME_TO": 'null',
                    "SHIPPING_INSTRUCTION": 'null',
                    "REMARKS": 'null',
                    "BONDED": 'null',
                    "TOTAL_PALLET": 'null',
                    "STORAGE_CHARGE": 'null',
                    "<Receive Reference Label-1>": 'null',
                    "<Receive Reference Label-2>": 'null',
                    "<Receive Reference Label-3>": 'null',
                    "<Receive Reference Label-4>": 'null',
                    "<Release Header User Defined-01>": 'null',
                    "<Release Header User Defined-02>": 'null',
                    "<Release Header User Defined-03>": 'null',
                    "<Release Header User Defined-04>": 'null',
                    "<Release Header User Defined-05>": 'null',
                    "<Release Header User Defined-06>": 'null',
                    "<Release Header User Defined-07>": 'null',
                    "<Release Header User Defined-08>": 'null',
                    "<Release Header User Defined-09>": 'null',
                    "<Release Header User Defined-10>": 'null',
                    "<Release Header User Defined-11>": 'null',
                    "<Release Header User Defined-12>": 'null',
                    "<Release Header User Defined-13>": 'null',
                    "<Release Header User Defined-14>": 'null',
                    "<Release Header User Defined-15>": 'null',
                    "<Receive Header User Defined-01>": 'null',
                    "<Receive Header User Defined-02>": 'null',
                    "<Receive Header User Defined-03>": 'null',
                    "<Receive Header User Defined-04>": 'null',
                    "<Receive Header User Defined-05>": 'null',
                    "<Receive Header User Defined-06>": 'null',
                    "<Receive Header User Defined-07>": 'null',
                    "<Receive Header User Defined-08>": 'null',
                    "<Receive Header User Defined-09>": 'null',
                    "<Receive Header User Defined-10>": 'null',
                    "<Receive Header User Defined-11>": 'null',
                    "<Receive Header User Defined-12>": 'null',
                    "<Receive Header User Defined-13>": 'null',
                    "<Receive Header User Defined-14>": 'null',
                    "<Receive Header User Defined-15>": 'null',
                    "DETAIL": [
                        {
                        "SKU_CODE": "123456",
                        "RELEASE_QTY": 1,
                        "PRODUCT_TYPE": 'null',
                        "PACK_CODE": 'null',
                        "PACK_QTY": 'null',
                        "PALLET_ID": 'null',
                        "CARTON_ID": 'null',
                        "EXPIRY_DATE": 'null',
                        "MANUF_DATE": 'null',
                        "LOCATION_CODE": 'null',
                        "LOT_NO": 'null',
                        "REMARKS": 'null',
                        "DEBOM": 'null',
                        "SYS_ID": 'null',
                        "<Release User Defined-01>": 'null',
                        "<Release User Defined-02>": 'null',
                        "<Release User Defined-03>": 'null',
                        "<Release User Defined-04>": 'null',
                        "<Release User Defined-05>": 'null',
                        "<Release User Defined-06>": 'null',
                        "<Release User Defined-07>": 'null',
                        "<Release User Defined-08>": 'null',
                        "<Release User Defined-09>": 'null',
                        "<Release User Defined-10>": 'null',
                        "<Release User Defined-11>": 'null',
                        "<Release User Defined-12>": 'null',
                        "<Release User Defined-13>": 'null',
                        "<Release User Defined-14>": 'null',
                        "<Release User Defined-15>": 'null',
                        "<Release User Defined-16>": 'null',
                        "<Release User Defined-17>": 'null',
                        "<Release User Defined-18>": 'null',
                        "<Release User Defined-19>": 'null',
                        "<Release User Defined-20>": 'null',
                        "<Release User Defined-21>": 'null',
                        "<Release User Defined-22>": 'null',
                        "<Release User Defined-23>": 'null',
                        "<Release User Defined-24>": 'null',
                        "<Release User Defined-25>": 'null',
                        "<Release User Defined-26>": 'null',
                        "<Release User Defined-27>": 'null',
                        "<Release User Defined-28>": 'null',
                        "<Release User Defined-29>": 'null',
                        "<Release User Defined-30>": 'null',
                        "<Receive User Defined-01>": 'null',
                        "<Receive User Defined-02>": 'null',
                        "<Receive User Defined-03>": 'null',
                        "<Receive User Defined-04>": 'null',
                        "<Receive User Defined-05>": 'null',
                        "<Receive User Defined-06>": 'null',
                        "<Receive User Defined-07>": 'null',
                        "<Receive User Defined-08>": 'null',
                        "<Receive User Defined-09>": 'null',
                        "<Receive User Defined-10>": 'null',
                        "<Receive User Defined-11>": 'null',
                        "<Receive User Defined-12>": 'null',
                        "<Receive User Defined-13>": 'null',
                        "<Receive User Defined-14>": 'null',
                        "<Receive User Defined-15>": 'null',
                        "<Receive User Defined-16>": 'null',
                        "<Receive User Defined-17>": 'null',
                        "<Receive User Defined-18>": 'null',
                        "<Receive User Defined-19>": 'null',
                        "<Receive User Defined-20>": 'null',
                        "<Receive User Defined-21>": 'null',
                        "<Receive User Defined-22>": 'null',
                        "<Receive User Defined-23>": 'null',
                        "<Receive User Defined-24>": 'null',
                        "<Receive User Defined-25>": 'null',
                        "<Receive User Defined-26>": 'null',
                        "<Receive User Defined-27>": 'null',
                        "<Receive User Defined-28>": 'null',
                        "<Receive User Defined-29>": 'null',
                        "<Receive User Defined-30>": 'null'
                        }
                    ]
                }
            ]
        }
    return CRE_PSO_JOB

def create_or_update_partner():
    COU_partner = {
        "DATA": [
            {
            "ACTIVE": True,
            "CODE": "PARTNER01",
            "COMPANY_NAME": "COM01",
            "ADDRESS": 'null',
            "ADDRESS2": 'null',
            "AREA1": 'null',
            "AREA2": 'null',
            "AREA3": 'null',
            "AREA4": 'null',
            "ZONE1": 'null',
            "ZONE2": 'null',
            "REGION1": 'null',
            "REGION2": 'null',
            "ZIP": 'null',
            "COUNTRY": 'null',
            "CONTACT_NAME": 'null',
            "CONTACT_PHONE": 'null',
            "CONTACT_EMAIL": 'null',
            "NOTE": 'null',
            "REF_TYPE": [
                {
                "TYPE": "P",
                "INFORM_EMAIL": True
                }
            ]
            }
        ]
        }
    return COU_partner

def select_inventory_list():
    SLL = {
                "DATA": [
                    {
                    "COUNT": 1,
                    "PAGE": {
                        "CURRENT": 1,
                        "FIRST": 1,
                        "LAST": 1,
                        "NEXT": 1,
                        "PREV": 1,
                        "SIZE": 10,
                        "TOTAL": 1
                    },
                    "DATA": [
                        {
                        "STORER_CODE": "STR000060",
                        "WH_CODE": "WH01",
                        "SKU_CODE": "PILLOWB001",
                        "SKU_DESC": "PILLOWB001",
                        "SKU_DESC_LOCAL": "หมอน",
                        "PRODUCT_TYPE": "FG",
                        "PALLET_ID": "q",
                        "CARTON_ID": 'null',
                        "LOT_NO": 'null',
                        "RECEIVED_DATE": "2021-01-15T03:11:49.392Z",
                        "EXPIRY_DATE": 'null',
                        "MANUF_DATE": 'null',
                        "RETURN_DATE": 'null',
                        "GOOD_CONDITION": "G",
                        "RECEIVE_QTY": 100,
                        "DAMAGED_QTY": 0,
                        "AVAILABLE_QTY": 80,
                        "ON_HAND_QTY": 100,
                        "HOLD_QTY": 20,
                        "HOLD_REASON_CODE": "FREEZ",
                        "CREATE_DATE": "2021-01-15T03:13:06.365Z",
                        "MODIFY_DATE": "2021-10-04T12:23:08.938Z",
                        "PACK_CODE": "PCS",
                        "PACK_QTY": 1,
                        "PRICE": 0,
                        "LENGTH": 1,
                        "WIDTH": 1,
                        "HEIGHT": 1,
                        "UNIT_CUB": 0.1,
                        "WEIGHT_UOM": "KG",
                        "VOLUME_UOM": "CBM",
                        "LENGTH_UOM": "CM",
                        "GROSS_WEIGHT": 1,
                        "NET_WEIGHT": 1,
                        "Rec1 No": 'null',
                        "RecHU1 No": 'null',
                        "HREC16": 'null',
                        "RecU1 No": 'null'
                        }
                    ]
                }
            ]
        }
    return SLL

def select_goods_receive_by_job():
    SGReceice_BY_JOB = {
            "DATA": [
                {
                "STORER_CODE": "STR000060",
                "WH_CODE": "WH01",
                "RECEIVE_KEY": "0000134340",
                "BATCH_NO": 1,
                "STATUS_CODE": "CLOSED",
                "Rec1 No": "1345",
                "TP_VEHICLE_NO": 'null',
                "TP_CARRIER": 'null',
                "TP_CONTAINER_NO_1": 'null',
                "TP_CONTAINER_TYPE_1": 'null',
                "TP_SEAL_NO_1": 'null',
                "TP_CONTAINER_NO_2": 'null',
                "TP_CONTAINER_TYPE_2": 'null',
                "TP_SEAL_NO_2": 'null',
                "TP_CONTAINER_NO_3": 'null',
                "TP_CONTAINER_TYPE_3": 'null',
                "TP_SEAL_NO_3": 'null',
                "TP_AIRWAYBILL": 'null',
                "TP_BILL_OF_LANDING": 'null',
                "TP_ORIGIN": 'null',
                "TP_VESSEL": 'null',
                "TP_PORT_OF_LANDING": 'null',
                "TP_PORT_DISCHARGE": 'null',
                "TP_VOYAGE": 'null',
                "TP_ETA": 'null',
                "RECEIVING_START_DATE": 'null',
                "RECEIVED_DATE": "2020-11-08T06:35:03.570Z",
                "PUTAWAY_START_DATE": 'null',
                "PUTAWAY_DATE": "2020-11-08T06:36:16.550Z",
                "PUTAWAY_BY": "ft",
                "CLOSED_DATE": "2020-11-08T06:36:40.968Z",
                "SUP_CODE": 'null',
                "SUP_COMPANY": "******",
                "SUP_ADDRESS": "******",
                "SUP_ADDRESS2": "******",
                "SUP_AREA1": "******",
                "SUP_AREA2": "******",
                "SUP_AREA3": "******",
                "SUP_AREA4": "******",
                "SUP_ZONE1": "******",
                "SUP_ZONE2": "******",
                "SUP_REGION1": "******",
                "SUP_REGION2": "******",
                "SUP_COUNTRY": "******",
                "SUP_ZIP": "******",
                "SUP_CONTACT_NAME": "******",
                "SUP_CONTACT_PHONE": "******",
                "SUP_CONTACT_EMAIL": "******",
                "SUP_NOTE": 'null',
                "BONDED": False,
                "TOTAL_PALLET": 1,
                "STORAGE_CHARGE": True,
                "RETURN_DATE": 'null',
                "REMARKS": 'null',
                "RECEIVED_SIGNED": 'null',
                "VERIFY_SIGNED": 'null',
                "RecHU1 No": 'null',
                "HUSER_DEFINED_16": 'null',
                "IMG_TRUCK_01": 'null',
                "IMG_TRUCK_02": 'null',
                "IMG_TRUCK_03": 'null',
                "IMG_TRUCK_04": 'null',
                "IMG_TRUCK_05": 'null',
                "IMG_TRUCK_06": 'null',
                "IMG_TRUCK_07": 'null',
                "IMG_TRUCK_08": 'null',
                "IMG_TRUCK_09": 'null',
                "IMG_TRUCK_10": 'null',
                "IMG_TRUCK_THUMB_01": 'null',
                "IMG_TRUCK_THUMB_02": 'null',
                "IMG_TRUCK_THUMB_03": 'null',
                "IMG_TRUCK_THUMB_04": 'null',
                "IMG_TRUCK_THUMB_05": 'null',
                "IMG_TRUCK_THUMB_06": 'null',
                "IMG_TRUCK_THUMB_07": 'null',
                "IMG_TRUCK_THUMB_08": 'null',
                "IMG_TRUCK_THUMB_09": 'null',
                "IMG_TRUCK_THUMB_10": 'null',
                "IMG_GOODS_01": 'null',
                "IMG_GOODS_02": 'null',
                "IMG_GOODS_03": 'null',
                "IMG_GOODS_04": 'null',
                "IMG_GOODS_05": 'null',
                "IMG_GOODS_06": 'null',
                "IMG_GOODS_07": 'null',
                "IMG_GOODS_08": 'null',
                "IMG_GOODS_09": 'null',
                "IMG_GOODS_10": 'null',
                "IMG_GOODS_THUMB_01": 'null',
                "IMG_GOODS_THUMB_02": 'null',
                "IMG_GOODS_THUMB_03": 'null',
                "IMG_GOODS_THUMB_04": 'null',
                "IMG_GOODS_THUMB_05": 'null',
                "IMG_GOODS_THUMB_06": 'null',
                "IMG_GOODS_THUMB_07": 'null',
                "IMG_GOODS_THUMB_08": 'null',
                "IMG_GOODS_THUMB_09": 'null',
                "IMG_GOODS_THUMB_10": 'null',
                "CREATE_BY": "ft",
                "MODIFY_BY": "ft",
                "CREATE_DATE": "2020-11-08T06:35:05.843Z",
                "MODIFY_DATE": "2020-11-08T06:36:40.969Z",
                "DELETE_DATE": 'null',
                "DETAIL": [
                    {
                    "SYS_ID": "0000003LCW",
                    "LINE_SEQ": 1,
                    "PRODUCT_TYPE": "FG",
                    "PALLET_ID": "AAQ",
                    "CARTON_ID": 'null',
                    "MANUF_DATE": 'null',
                    "EXPIRY_DATE": 'null',
                    "LENGTH": 1,
                    "WIDTH": 1,
                    "HEIGHT": 1,
                    "LENGTH_UOM": "CM",
                    "UNIT_CUB": 0.000001,
                    "VOLUME_UOM": "CBM",
                    "GROSS_WEIGHT": 1,
                    "NET_WEIGHT": 1,
                    "WEIGHT_UOM": "KG",
                    "GOOD_QTY": 100,
                    "DAMAGED_QTY": 0,
                    "PACK_CODE": "PCS",
                    "PACK_QTY": 1,
                    "CONFIRM_PUTAWAY_QTY": 100,
                    "HOLD": False,
                    "REMARKS": 'null',
                    "ASN_LINE_SEQ": 'null',
                    "DEBOM": False,
                    "NON_CONFORMANCE": 'null',
                    "NON_CONFORMANCE_REMARK": 'null',
                    "LOT_NO": 'null',
                    "RecU1 No": 'null',
                    "PRICE": 0,
                    "CREATE_BY": "ft",
                    "MODIFY_BY": "ft",
                    "CREATE_DATE": "2020-11-08T06:35:15.254Z",
                    "MODIFY_DATE": "2020-11-08T06:36:34.035Z",
                    "DELETE_DATE": 'null',
                    "SKU_CODE": "PILLOWB001",
                    "LOCATION_CODE": "LOC_WH01",
                    "HOLD_REASON_CODE": 'null'
                    }
                ]
                }
            ]
            }
    return SGReceice_BY_JOB

def Cancel_DSO():
    CD = {
                "DATA": [
                    {
                "<Release Reference Label-1>": "REL-2735287259",
                "<Release Reference Label-2>": "REL-7563430644",
                "<Release Reference Label-3>": "REL-9045200998",
                "<Release Reference Label-4>": "REL-6992735291"
                }
            ]
        }
    return CD

def Update_Invoice():
    UI = {
                "DATA": [
                    {
                        "<Release Reference Label-1>": "REL-6360249344",
                        "<Release Reference Label-2>": "REL-8065676721",
                        "<Release Reference Label-3>": "REL-1933819033",
                        "<Release Reference Label-4>": "REL-2768953543",
                        "INVOICE_DATA": {
                            "PAYMENT_TYPE": 'null',
                            "INV_FORMAT_FILE_DESTINATION": 'null',
                            "INVOICE_DATE": 'null',
                            "SALE_ORDER_NO": 'null',
                            "CUSTOMER_PHONE_NUMBER": 'null',
                            "POSTING_DATE": 'null',
                            "DUE_DATE": 'null',
                            "CUSTOMER_PURCHASE_ORDER_REFERENCE": 'null',
                            "CUSTOMER_ID": 'null',
                            "CUSTOMER_CODE": 'null',
                            "CUSTOMER_TAX_ID": 'null',
                            "CUSTOMER_BRANCH": 'null',
                            "CUSTOMER_NAME": 'null',
                            "CUSTOMER_EMAIL": 'null',
                            "BILL_TO_NAME": 'null',
                            "BILL_TO_CUSTOMER_ID": 'null',
                            "BILL_TO_CUSTOMER_NUMBER": 'null',
                            "BILL_TO_ADDRESS_1": 'null',
                            "BILL_TO_ADDRESS_2": 'null',
                            "BILL_TO_CITY": 'null',
                            "BILL_TO_COUNTRY": 'null',
                            "BILL_TO_STATE": 'null',
                            "BILL_TO_POST_CODE": 'null',
                            "SHIP_TO_CODE": 'null',
                            "SHIP_TO_NAME": 'null',
                            "SHIP_TO_CONTACT": 'null',
                            "SHIP_TO_ADDRESS_1": 'null',
                            "SHIP_TO_ADDRESS_2": 'null',
                            "SHIP_TO_CITY": 'null',
                            "SHIP_TO_COUNTRY": 'null',
                            "SHIP_TO_STATE": 'null',
                            "SHIP_TO_POST_CODE": 'null',
                            "CURRENCY_CODE": 'null',
                            "PAYMENT_TERM": 'null',
                            "SALES_PERSON": 'null',
                            "TAX_CODE": 'null',
                            "TAX_PERCENT": 'null',
                            "PRICES_INCLUDE_TAX": 'null',
                            "REMAINING_AMOUNT": 'null',
                            "TOTAL_AMOUNT_BEFORE_DISCOUNT": 'null',
                            "DISCOUNT_AMOUNT": 'null',
                            "DISCOUNT_APPLIED_BEFORE_TAX": 'null',
                            "TOTAL_AMOUNT_BEFORE_TAX": 'null',
                            "TOTAL_TAX_AMOUNT": 'null',
                            "TOTAL_AMOUNT_INCLUDING_TAX": 'null',
                            "DEPOSIT_AMOUNT": 'null',
                            "STATUS": 'null',
                            "<Release Header User Defined-01>": 'null',
                            "<Release Header User Defined-02>": 'null',
                            "<Release Header User Defined-03>": 'null',
                            "<Release Header User Defined-04>": 'null',
                            "<Release Header User Defined-05>": 'null',
                            "<Release Header User Defined-06>": 'null',
                            "<Release Header User Defined-07>": 'null',
                            "<Release Header User Defined-08>": 'null',
                            "<Release Header User Defined-09>": 'null',
                            "<Release Header User Defined-10>": 'null',
                            "<Release Header User Defined-11>": 'null',
                            "<Release Header User Defined-12>": 'null',
                            "<Release Header User Defined-13>": 'null',
                            "<Release Header User Defined-14>": 'null',
                            "<Release Header User Defined-15>": 'null',
                            "DETAIL": [
                            {
                                "SEQUENCE": 'null',
                                "ITEM_CODE": 'null',
                                "ITEM_DESC": 'null',
                                "PACK_CODE": 'null',
                                "UNIT_PRICE": 'null',
                                "QUANTITY": 'null',
                                "DISCOUNT_AMOUNT": 'null',
                                "DISCOUNT_PERCENT": 'null',
                                "DISCOUNT_APPLIED_BEFORE_TAX": 'null',
                                "AMOUNT_BEFORE_TAX": 'null',
                                "TAX_CODE": 'null',
                                "TAX_PERCENT": 'null',
                                "LINE_AMOUNT_BEFORE_DISCOUNT": 'null',
                                "INVOICE_DISCOUNT_ALLOCATION": 'null',
                                "LINE_AMOUNT_BEFORE_TAX": 'null',
                                "LINE_TAX_AMOUNT": 'null',
                                "LINE_AMOUNT_INCLUDING_TAX": 'null',
                                "<Release User Defined-01>": 'null',
                                "<Release User Defined-02>": 'null',
                                "<Release User Defined-03>": 'null',
                                "<Release User Defined-04>": 'null',
                                "<Release User Defined-05>": 'null',
                                "<Release User Defined-06>": 'null',
                                "<Release User Defined-07>": 'null',
                                "<Release User Defined-08>": 'null',
                                "<Release User Defined-09>": 'null',
                                "<Release User Defined-10>": 'null',
                                "<Release User Defined-11>": 'null',
                                "<Release User Defined-12>": 'null',
                                "<Release User Defined-13>": 'null',
                                "<Release User Defined-14>": 'null',
                                "<Release User Defined-15>": 'null',
                                "<Release User Defined-16>": 'null',
                                "<Release User Defined-17>": 'null',
                                "<Release User Defined-18>": 'null',
                                "<Release User Defined-19>": 'null',
                                "<Release User Defined-20>": 'null',
                                "<Release User Defined-21>": 'null',
                                "<Release User Defined-22>": 'null',
                                "<Release User Defined-23>": 'null',
                                "<Release User Defined-24>": 'null',
                                "<Release User Defined-25>": 'null',
                                "<Release User Defined-26>": 'null',
                                "<Release User Defined-27>": 'null',
                                "<Release User Defined-28>": 'null',
                                "<Release User Defined-29>": 'null',
                                "<Release User Defined-30>": 'null'
                            }
                        ]
                    }
                }
            ]
        }
    return UI

def Update_Consignee_and_ShipTo():
    UC_and_SHIPTO = {
                    "DATA":[
                    {
                    "<Release Reference Label-1>": "REL-8714287303",
                    "<Release Reference Label-2>": "REL-7166195423",
                    "<Release Reference Label-3>": "REL-2579928879",
                    "<Release Reference Label-4>": "REL-8804956474",
                    "CON_CODE": 'null',
                    "CON_COMPANY": 'null',
                    "CON_TAX_NO": 'null',
                    "CON_BRANCH": 'null',
                    "CON_ADDRESS": 'null',
                    "CON_ADDRESS2": 'null',
                    "CON_AREA1": 'null',
                    "CON_AREA2": 'null',
                    "CON_AREA3": 'null',
                    "CON_AREA4": 'null',
                    "CON_ZONE1": 'null',
                    "CON_ZONE2": 'null',
                    "CON_REGION1": 'null',
                    "CON_REGION2": 'null',
                    "CON_COUNTRY": 'null',
                    "CON_ZIP": 'null',
                    "CON_CONTACT_NAME": 'null',
                    "CON_CONTACT_PHONE": 'null',
                    "CON_CONTACT_EMAIL": 'null',
                    "CON_NOTE": 'null',
                    "ST_CODE": 'null',
                    "ST_COMPANY": 'null',
                    "ST_ADDRESS": 'null',
                    "ST_ADDRESS2": 'null',
                    "ST_AREA1": 'null',
                    "ST_AREA2": 'null',
                    "ST_AREA3": 'null',
                    "ST_AREA4": 'null',
                    "ST_ZONE1": 'null',
                    "ST_ZONE2": 'null',
                    "ST_REGION1": 'null',
                    "ST_REGION2": 'null',
                    "ST_COUNTRY": 'null',
                    "ST_ZIP": 'null',
                    "ST_CONTACT_NAME": 'null',
                    "ST_CONTACT_PHONE": 'null',
                    "ST_CONTACT_EMAIL": 'null',
                    "ST_NOTE": 'null'
                    }
                ]
            }
    return UC_and_SHIPTO

def create_DSO_Job():
    CRE_DSO_JOB = {
                    "DATA": [
                        {
                        "<Release Reference Label-1>": "REL-0682578235",
                        "<Release Reference Label-2>": "REL-2624922914",
                        "<Release Reference Label-3>": "REL-9766789709",
                        "<Release Reference Label-4>": "REL-5069149869",
                        "REL_PREFIX": 'null',
                        "TEAM": 'null',
                        "EXP_RELEASE_DATE": 'null',
                        "INVOICE_NO": 'null',
                        "TP_VEHICLE_NO": 'null',
                        "TP_BOOKING": 'null',
                        "TP_CARRIER": 'null',
                        "TP_CONTAINER_NO_1": 'null',
                        "TP_CONTAINER_TYPE_1": 'null',
                        "TP_SEAL_NO_1": 'null',
                        "TP_CONTAINER_NO_2": 'null',
                        "TP_CONTAINER_TYPE_2": 'null',
                        "TP_SEAL_NO_2": 'null',
                        "TP_CONTAINER_NO_3": 'null',
                        "TP_CONTAINER_TYPE_3": 'null',
                        "TP_SEAL_NO_3": 'null',
                        "TP_AIRWAYBILL": 'null',
                        "TP_BILL_OF_LANDING": 'null',
                        "TP_ORIGIN": 'null',
                        "TP_VESSEL": 'null',
                        "TP_PORT_OF_LANDING": 'null',
                        "TP_PORT_DISCHARGE": 'null',
                        "TP_VOYAGE": 'null',
                        "TP_ETD": 'null',
                        "CON_CODE": 'null',
                        "CON_COMPANY": 'null',
                        "CON_TAX_NO": 'null',
                        "CON_BRANCH": 'null',
                        "CON_ADDRESS": 'null',
                        "CON_ADDRESS2": 'null',
                        "CON_AREA1": 'null',
                        "CON_AREA2": 'null',
                        "CON_AREA3": 'null',
                        "CON_AREA4": 'null',
                        "CON_ZONE1": 'null',
                        "CON_ZONE2": 'null',
                        "CON_REGION1": 'null',
                        "CON_REGION2": 'null',
                        "CON_COUNTRY": 'null',
                        "CON_ZIP": 'null',
                        "CON_CONTACT_NAME": 'null',
                        "CON_CONTACT_PHONE": 'null',
                        "CON_CONTACT_EMAIL": 'null',
                        "CON_NOTE": 'null',
                        "ST_CODE": 'null',
                        "ST_COMPANY": 'null',
                        "ST_ADDRESS": 'null',
                        "ST_ADDRESS2": 'null',
                        "ST_AREA1": 'null',
                        "ST_AREA2": 'null',
                        "ST_AREA3": 'null',
                        "ST_AREA4": 'null',
                        "ST_ZONE1": 'null',
                        "ST_ZONE2": 'null',
                        "ST_REGION1": 'null',
                        "ST_REGION2": 'null',
                        "ST_COUNTRY": 'null',
                        "ST_ZIP": 'null',
                        "ST_CONTACT_NAME": 'null',
                        "ST_CONTACT_PHONE": 'null',
                        "ST_CONTACT_EMAIL": 'null',
                        "ST_NOTE": 'null',
                        "DEL_CONSIGNMENT": 'null',
                        "DEL_URGENT_ORDER": 'null',
                        "DEL_COD": 'null',
                        "DEL_COD_AMOUNT": 'null',
                        "DELIVERY_TIME_FROM": 'null',
                        "DELIVERY_TIME_TO": 'null',
                        "SHIPPING_INSTRUCTION": 'null',
                        "REMARKS": 'null',
                        "BONDED": 'null',
                        "TOTAL_PALLET": 'null',
                        "STORAGE_CHARGE": 'null',
                        "IMG_TRUCK_01": 'null',
                        "IMG_TRUCK_02": 'null',
                        "IMG_TRUCK_03": 'null',
                        "IMG_TRUCK_04": 'null',
                        "IMG_TRUCK_05": 'null',
                        "IMG_TRUCK_06": 'null',
                        "IMG_TRUCK_07": 'null',
                        "IMG_TRUCK_08": 'null',
                        "IMG_TRUCK_09": 'null',
                        "IMG_TRUCK_10": 'null',
                        "IMG_GOODS_01": 'null',
                        "IMG_GOODS_02": 'null',
                        "IMG_GOODS_03": 'null',
                        "IMG_GOODS_04": 'null',
                        "IMG_GOODS_05": 'null',
                        "IMG_GOODS_06": 'null',
                        "IMG_GOODS_07": 'null',
                        "IMG_GOODS_08": 'null',
                        "IMG_GOODS_09": 'null',
                        "IMG_GOODS_10": 'null',
                        "<Release Header User Defined-01>": 'null',
                        "<Release Header User Defined-02>": 'null',
                        "<Release Header User Defined-03>": 'null',
                        "<Release Header User Defined-04>": 'null',
                        "<Release Header User Defined-05>": 'null',
                        "<Release Header User Defined-06>": 'null',
                        "<Release Header User Defined-07>": 'null',
                        "<Release Header User Defined-08>": 'null',
                        "<Release Header User Defined-09>": 'null',
                        "<Release Header User Defined-10>": 'null',
                        "<Release Header User Defined-11>": 'null',
                        "<Release Header User Defined-12>": 'null',
                        "<Release Header User Defined-13>": 'null',
                        "<Release Header User Defined-14>": 'null',
                        "<Release Header User Defined-15>": 'null',
                        "DETAIL": [
                            {
                            "SKU_CODE": "123456",
                            "RELEASE_QTY": 1,
                            "PRODUCT_TYPE": 'null',
                            "PACK_CODE": 'null',
                            "PACK_QTY": 'null',
                            "PALLET_ID": 'null',
                            "CARTON_ID": 'null',
                            "EXPIRY_DATE": 'null',
                            "MANUF_DATE": 'null',
                            "PICK_BY_CODE": 'null',
                            "LOCATION_CODE": 'null',
                            "LOT_NO": 'null',
                            "REMARKS": 'null',
                            "DEBOM": 'null',
                            "SYS_ID": 'null',
                            "<Release User Defined-01>": 'null',
                            "<Release User Defined-02>": 'null',
                            "<Release User Defined-03>": 'null',
                            "<Release User Defined-04>": 'null',
                            "<Release User Defined-05>": 'null',
                            "<Release User Defined-06>": 'null',
                            "<Release User Defined-07>": 'null',
                            "<Release User Defined-08>": 'null',
                            "<Release User Defined-09>": 'null',
                            "<Release User Defined-10>": 'null',
                            "<Release User Defined-11>": 'null',
                            "<Release User Defined-12>": 'null',
                            "<Release User Defined-13>": 'null',
                            "<Release User Defined-14>": 'null',
                            "<Release User Defined-15>": 'null',
                            "<Release User Defined-16>": 'null',
                            "<Release User Defined-17>": 'null',
                            "<Release User Defined-18>": 'null',
                            "<Release User Defined-19>": 'null',
                            "<Release User Defined-20>": 'null',
                            "<Release User Defined-21>": 'null',
                            "<Release User Defined-22>": 'null',
                            "<Release User Defined-23>": 'null',
                            "<Release User Defined-24>": 'null',
                            "<Release User Defined-25>": 'null',
                            "<Release User Defined-26>": 'null',
                            "<Release User Defined-27>": 'null',
                            "<Release User Defined-28>": 'null',
                            "<Release User Defined-29>": 'null',
                            "<Release User Defined-30>": 'null'
                            }
                        ]
                    }
                ]
            }
    return CRE_DSO_JOB


def select_summary_of_DSO():
    SS_DSO = {
                "DATA" : [
                {
                "JOB_COUNT": 10,
                "JOB_QTY": 200
                }
            ]
        }
    return SS_DSO


def select_summary_of_ASN():
    SS_ASN = {
                "DATA" : [
                {
                "JOB_COUNT": 10,
                "JOB_QTY": 200
                }
            ]
        }
    return SS_ASN

def select_confirm_shipped_by_job():
    SCShipped_BY_JOB = {
                    "DATA": [
                        {
                        "STORER_CODE": "STR000060",
                        "WH_CODE": "WH01",
                        "RELEASE_KEY": "0000019990",
                        "BATCH_NO": 1,
                        "STATUS_CODE": "CLOSED",
                        "REL_PREFIX": 'null',
                        "TEAM": 'null',
                        "EXP_RELEASE_DATE": "2020-11-08T06:36:48.759Z",
                        "DRAFT_DATE": "2020-11-08T06:36:52.303Z",
                        "OPENED_DATE": "2020-11-08T06:36:48.759Z",
                        "ALLOCATING_DATE": "2020-11-08T06:37:33.866Z",
                        "ALLOCATED_DATE": "2020-11-08T06:37:46.542Z",
                        "PICKING_DATE": "2020-11-08T06:37:52.042Z",
                        "PICKED_DATE": "2020-11-08T06:37:53.646Z",
                        "PACKING_DATE": "2020-11-08T06:37:53.646Z",
                        "PACKED_DATE": "2020-11-08T06:37:53.646Z",
                        "READY_TO_SHIP_DATE": "2020-11-08T06:37:53.646Z",
                        "RELEASING_DATE": "2020-11-08T06:37:53.646Z",
                        "CLOSED_DATE": "2020-11-08T06:37:53.646Z",
                        "IN_TRANSIT_DATE": 'null',
                        "POD_DATE": 'null',
                        "Rel1 No": "17562",
                        "Rec1 No": 'null',
                        "INVOICE_NO": 'null',
                        "TP_VEHICLE_NO": 'null',
                        "TP_BOOKING": 'null',
                        "TP_CARRIER": 'null',
                        "TP_CONTAINER_NO_1": 'null',
                        "TP_CONTAINER_TYPE_1": 'null',
                        "TP_SEAL_NO_1": 'null',
                        "TP_CONTAINER_NO_2": 'null',
                        "TP_CONTAINER_TYPE_2": 'null',
                        "TP_SEAL_NO_2": 'null',
                        "TP_CONTAINER_NO_3": 'null',
                        "TP_CONTAINER_TYPE_3": 'null',
                        "TP_SEAL_NO_3": 'null',
                        "TP_AIRWAYBILL": 'null',
                        "TP_BILL_OF_LANDING": 'null',
                        "TP_ORIGIN": 'null',
                        "TP_VESSEL": 'null',
                        "TP_PORT_OF_LANDING": 'null',
                        "TP_PORT_DISCHARGE": 'null',
                        "TP_VOYAGE": 'null',
                        "TP_ETD": 'null',
                        "CON_CODE": 'null',
                        "CON_COMPANY": "******",
                        "CON_ADDRESS": "******",
                        "CON_ADDRESS2": "******",
                        "CON_AREA1": "******",
                        "CON_AREA2": "******",
                        "CON_AREA3": "******",
                        "CON_AREA4": "******",
                        "CON_ZONE1": "******",
                        "CON_ZONE2": "******",
                        "CON_REGION1": "******",
                        "CON_REGION2": "******",
                        "CON_COUNTRY": "******",
                        "CON_ZIP": "******",
                        "CON_CONTACT_NAME": "******",
                        "CON_CONTACT_PHONE": "******",
                        "CON_CONTACT_EMAIL": "******",
                        "CON_NOTE": 'null',
                        "ST_CODE": 'null',
                        "ST_COMPANY": "******",
                        "ST_ADDRESS": "******",
                        "ST_ADDRESS2": "******",
                        "ST_AREA1": "******",
                        "ST_AREA2": "******",
                        "ST_AREA3": "******",
                        "ST_AREA4": "******",
                        "ST_ZONE1": "******",
                        "ST_ZONE2": "******",
                        "ST_REGION1": "******",
                        "ST_REGION2": "******",
                        "ST_COUNTRY": "******",
                        "ST_ZIP": "******",
                        "ST_CONTACT_NAME": "******",
                        "ST_CONTACT_PHONE": "******",
                        "ST_CONTACT_EMAIL": "******",
                        "ST_NOTE": 'null',
                        "DEL_CONSIGNMENT": 'null',
                        "DEL_URGENT_ORDER": 'null',
                        "DEL_COD": 'null',
                        "DEL_COD_AMOUNT": 'null',
                        "DELIVERY_TIME_FROM": 'null',
                        "DELIVERY_TIME_TO": 'null',
                        "SHIPPING_INSTRUCTION": 'null',
                        "REMARKS": 'null',
                        "BONDED": False,
                        "TOTAL_PALLET": 0,
                        "STORAGE_CHARGE": True,
                        "IMG_TRUCK_01": 'null',
                        "IMG_TRUCK_02": 'null',
                        "IMG_TRUCK_03": 'null',
                        "IMG_TRUCK_04": 'null',
                        "IMG_TRUCK_05": 'null',
                        "IMG_TRUCK_06": 'null',
                        "IMG_TRUCK_07": 'null',
                        "IMG_TRUCK_08": 'null',
                        "IMG_TRUCK_09": 'null',
                        "IMG_TRUCK_10": 'null',
                        "IMG_TRUCK_THUMB_01": 'null',
                        "IMG_TRUCK_THUMB_02": 'null',
                        "IMG_TRUCK_THUMB_03": 'null',
                        "IMG_TRUCK_THUMB_04": 'null',
                        "IMG_TRUCK_THUMB_05": 'null',
                        "IMG_TRUCK_THUMB_06": 'null',
                        "IMG_TRUCK_THUMB_07": 'null',
                        "IMG_TRUCK_THUMB_08": 'null',
                        "IMG_TRUCK_THUMB_09": 'null',
                        "IMG_TRUCK_THUMB_10": 'null',
                        "IMG_GOODS_01": 'null',
                        "IMG_GOODS_02": 'null',
                        "IMG_GOODS_03": 'null',
                        "IMG_GOODS_04": 'null',
                        "IMG_GOODS_05": 'null',
                        "IMG_GOODS_06": 'null',
                        "IMG_GOODS_07": 'null',
                        "IMG_GOODS_08": 'null',
                        "IMG_GOODS_09": 'null',
                        "IMG_GOODS_10": 'null',
                        "IMG_GOODS_THUMB_01": 'null',
                        "IMG_GOODS_THUMB_02": 'null',
                        "IMG_GOODS_THUMB_03": 'null',
                        "IMG_GOODS_THUMB_04": 'null',
                        "IMG_GOODS_THUMB_05": 'null',
                        "IMG_GOODS_THUMB_06": 'null',
                        "IMG_GOODS_THUMB_07": 'null',
                        "IMG_GOODS_THUMB_08": 'null',
                        "IMG_GOODS_THUMB_09": 'null',
                        "IMG_GOODS_THUMB_10": 'null',
                        "MKP_JOB_BRAND": 'null',
                        "MKP_JOB_NO": 'null',
                        "CREATE_BY": "ft",
                        "MODIFY_BY": "ft",
                        "CREATE_DATE": "2020-11-08T06:36:52.306Z",
                        "MODIFY_DATE": "2020-11-20T08:44:51.457Z",
                        "DELETE_DATE": 'null',
                        "DETAIL": [
                            {
                            "LINE_SEQ": 1,
                            "PRODUCT_TYPE": "FG",
                            "PACK_CODE": "PCS",
                            "PACK_QTY": 1,
                            "PALLET_ID": "AAQ",
                            "CARTON_ID": 'null',
                            "EXPIRY_DATE": 'null',
                            "MANUF_DATE": 'null',
                            "EXP_RELEASE_QTY": 1,
                            "RELEASE_QTY": 1,
                            "ALLOCATED_QTY": 0,
                            "PICKING_QTY": 0,
                            "PICKED_QTY": 0,
                            "PACKED_QTY": 0,
                            "SHIPPED_QTY": 1,
                            "RELEASE_QTY_DIFF": 0,
                            "LOT_NO": 'null',
                            "REMARKS": 'null',
                            "DEBOM": False,
                            "SYS_ID": 'null',
                            "MKP_JOB_DETAIL_NO": 'null',
                            "MKP_DEL_CONSIGNMENT": 'null',
                            "MKP_ST_LABEL": 'null',
                            "MKP_STATUS": 'null',
                            "MKP_INVOICE_NO": 'null',
                            "MKP_PRICE_AFTER_DISCOUNT": 'null',
                            "CREATE_BY": "ft",
                            "MODIFY_BY": "ft",
                            "CREATE_DATE": "2020-11-08T06:36:59.256Z",
                            "MODIFY_DATE": "2020-11-20T08:44:51.442Z",
                            "DELETE_DATE": 'null',
                            "SKU_CODE": "PILLOWB001",
                            "LOCATION_CODE": 'null',
                            "PICK_BY_CODE": "FIFO"
                            }
                        ]
                    }
                ]
            }
    return SCShipped_BY_JOB

def select_confirm_picked_by_job():
    SCPicked_BY_JOB = {
                    "DATA": [
                        {
                        "STORER_CODE": "STR000060",
                        "WH_CODE": "WH01",
                        "RELEASE_KEY": "0000019990",
                        "BATCH_NO": 1,
                        "STATUS_CODE": "PICKED",
                        "REL_PREFIX": 'null',
                        "TEAM": 'null',
                        "EXP_RELEASE_DATE": "2020-11-08T06:36:48.759Z",
                        "DRAFT_DATE": "2020-11-08T06:36:52.303Z",
                        "OPENED_DATE": "2020-11-08T06:36:48.759Z",
                        "ALLOCATING_DATE": "2020-11-08T06:37:33.866Z",
                        "ALLOCATED_DATE": "2020-11-08T06:37:46.542Z",
                        "PICKING_DATE": "2020-11-08T06:37:52.042Z",
                        "PICKED_DATE": "2020-11-08T06:37:53.646Z",
                        "PACKING_DATE": 'null',
                        "PACKED_DATE": 'null',
                        "READY_TO_SHIP_DATE": 'null',
                        "RELEASING_DATE": 'null',
                        "CLOSED_DATE": 'null',
                        "IN_TRANSIT_DATE": 'null',
                        "POD_DATE": 'null',
                        "Rel1 No": "17562",
                        "Rec1 No": 'null',
                        "INVOICE_NO": 'null',
                        "TP_VEHICLE_NO": 'null',
                        "TP_BOOKING": 'null',
                        "TP_CARRIER": 'null',
                        "TP_CONTAINER_NO_1": 'null',
                        "TP_CONTAINER_TYPE_1": 'null',
                        "TP_SEAL_NO_1": 'null',
                        "TP_CONTAINER_NO_2": 'null',
                        "TP_CONTAINER_TYPE_2": 'null',
                        "TP_SEAL_NO_2": 'null',
                        "TP_CONTAINER_NO_3": 'null',
                        "TP_CONTAINER_TYPE_3": 'null',
                        "TP_SEAL_NO_3": 'null',
                        "TP_AIRWAYBILL": 'null',
                        "TP_BILL_OF_LANDING": 'null',
                        "TP_ORIGIN": 'null',
                        "TP_VESSEL": 'null',
                        "TP_PORT_OF_LANDING": 'null',
                        "TP_PORT_DISCHARGE": 'null',
                        "TP_VOYAGE": 'null',
                        "TP_ETD": 'null',
                        "CON_CODE": 'null',
                        "CON_COMPANY": "******",
                        "CON_ADDRESS": "******",
                        "CON_ADDRESS2": "******",
                        "CON_AREA1": "******",
                        "CON_AREA2": "******",
                        "CON_AREA3": "******",
                        "CON_AREA4": "******",
                        "CON_ZONE1": "******",
                        "CON_ZONE2": "******",
                        "CON_REGION1": "******",
                        "CON_REGION2": "******",
                        "CON_COUNTRY": "******",
                        "CON_ZIP": "******",
                        "CON_CONTACT_NAME": "******",
                        "CON_CONTACT_PHONE": "******",
                        "CON_CONTACT_EMAIL": "******",
                        "CON_NOTE": 'null',
                        "ST_CODE": 'null',
                        "ST_COMPANY": "******",
                        "ST_ADDRESS": "******",
                        "ST_ADDRESS2": "******",
                        "ST_AREA1": "******",
                        "ST_AREA2": "******",
                        "ST_AREA3": "******",
                        "ST_AREA4": "******",
                        "ST_ZONE1": "******",
                        "ST_ZONE2": "******",
                        "ST_REGION1": "******",
                        "ST_REGION2": "******",
                        "ST_COUNTRY": "******",
                        "ST_ZIP": "******",
                        "ST_CONTACT_NAME": "******",
                        "ST_CONTACT_PHONE": "******",
                        "ST_CONTACT_EMAIL": "******",
                        "ST_NOTE": 'null',
                        "DEL_CONSIGNMENT": 'null',
                        "DEL_URGENT_ORDER": 'null',
                        "DEL_COD": 'null',
                        "DEL_COD_AMOUNT": 'null',
                        "DELIVERY_TIME_FROM": 'null',
                        "DELIVERY_TIME_TO": 'null',
                        "SHIPPING_INSTRUCTION": 'null',
                        "REMARKS": 'null',
                        "BONDED": False,
                        "TOTAL_PALLET": 0,
                        "STORAGE_CHARGE": True,
                        "IMG_TRUCK_01": 'null',
                        "IMG_TRUCK_02": 'null',
                        "IMG_TRUCK_03": 'null',
                        "IMG_TRUCK_04": 'null',
                        "IMG_TRUCK_05": 'null',
                        "IMG_TRUCK_06": 'null',
                        "IMG_TRUCK_07": 'null',
                        "IMG_TRUCK_08": 'null',
                        "IMG_TRUCK_09": 'null',
                        "IMG_TRUCK_10": 'null',
                        "IMG_TRUCK_THUMB_01": 'null',
                        "IMG_TRUCK_THUMB_02": 'null',
                        "IMG_TRUCK_THUMB_03": 'null',
                        "IMG_TRUCK_THUMB_04": 'null',
                        "IMG_TRUCK_THUMB_05": 'null',
                        "IMG_TRUCK_THUMB_06": 'null',
                        "IMG_TRUCK_THUMB_07": 'null',
                        "IMG_TRUCK_THUMB_08": 'null',
                        "IMG_TRUCK_THUMB_09": 'null',
                        "IMG_TRUCK_THUMB_10": 'null',
                        "IMG_GOODS_01": 'null',
                        "IMG_GOODS_02": 'null',
                        "IMG_GOODS_03": 'null',
                        "IMG_GOODS_04": 'null',
                        "IMG_GOODS_05": 'null',
                        "IMG_GOODS_06": 'null',
                        "IMG_GOODS_07": 'null',
                        "IMG_GOODS_08": 'null',
                        "IMG_GOODS_09": 'null',
                        "IMG_GOODS_10": 'null',
                        "IMG_GOODS_THUMB_01": 'null',
                        "IMG_GOODS_THUMB_02": 'null',
                        "IMG_GOODS_THUMB_03": 'null',
                        "IMG_GOODS_THUMB_04": 'null',
                        "IMG_GOODS_THUMB_05": 'null',
                        "IMG_GOODS_THUMB_06": 'null',
                        "IMG_GOODS_THUMB_07": 'null',
                        "IMG_GOODS_THUMB_08": 'null',
                        "IMG_GOODS_THUMB_09": 'null',
                        "IMG_GOODS_THUMB_10": 'null',
                        "MKP_JOB_BRAND": 'null',
                        "MKP_JOB_NO": 'null',
                        "CREATE_BY": "ft",
                        "MODIFY_BY": "ft",
                        "CREATE_DATE": "2020-11-08T06:36:52.306Z",
                        "MODIFY_DATE": "2020-11-20T08:44:51.457Z",
                        "DELETE_DATE": 'null',
                        "DETAIL": [
                            {
                            "LINE_SEQ": 1,
                            "PRODUCT_TYPE": "FG",
                            "PACK_CODE": "PCS",
                            "PACK_QTY": 1,
                            "PALLET_ID": "AAQ",
                            "CARTON_ID": 'null',
                            "EXPIRY_DATE": 'null',
                            "MANUF_DATE": 'null',
                            "EXP_RELEASE_QTY": 1,
                            "RELEASE_QTY": 1,
                            "ALLOCATED_QTY": 0,
                            "PICKING_QTY": 0,
                            "PICKED_QTY": 0,
                            "PACKED_QTY": 1,
                            "SHIPPED_QTY": 0,
                            "RELEASE_QTY_DIFF": 0,
                            "LOT_NO": 'null',
                            "REMARKS": 'null',
                            "DEBOM": False,
                            "SYS_ID": 'null',
                            "MKP_JOB_DETAIL_NO": 'null',
                            "MKP_DEL_CONSIGNMENT": 'null',
                            "MKP_ST_LABEL": 'null',
                            "MKP_STATUS": 'null',
                            "MKP_INVOICE_NO": 'null',
                            "MKP_PRICE_AFTER_DISCOUNT": 'null',
                            "CREATE_BY": "ft",
                            "MODIFY_BY": "ft",
                            "CREATE_DATE": "2020-11-08T06:36:59.256Z",
                            "MODIFY_DATE": "2020-11-20T08:44:51.442Z",
                            "DELETE_DATE": 'null',
                            "SKU_CODE": "PILLOWB001",
                            "LOCATION_CODE": 'null',
                            "PICK_BY_CODE": "FIFO"
                            }
                        ]
                    }
                ]
            }
    return SCPicked_BY_JOB

def select_confirm_packed_by_job():
    SCPacked_BY_JOB = {
                "DATA": [
                    {
                    "STORER_CODE": "STR000060",
                    "WH_CODE": "WH01",
                    "RELEASE_KEY": "0000019989",
                    "BATCH_NO": 1,
                    "STATUS_CODE": "PACKED",
                    "REL_PREFIX": 'null',
                    "TEAM": 'null',
                    "EXP_RELEASE_DATE": "2020-11-08T06:36:48.759Z",
                    "DRAFT_DATE": "2020-11-08T06:36:52.303Z",
                    "OPENED_DATE": "2020-11-08T06:36:48.759Z",
                    "ALLOCATING_DATE": "2020-11-08T06:37:33.866Z",
                    "ALLOCATED_DATE": "2020-11-08T06:37:46.542Z",
                    "PICKING_DATE": "2020-11-08T06:37:52.042Z",
                    "PICKED_DATE": "2020-11-08T06:37:53.646Z",
                    "PACKING_DATE": "2020-11-08T06:55:13.989Z",
                    "PACKED_DATE": "2020-11-08T06:55:13.989Z",
                    "READY_TO_SHIP_DATE": 'null',
                    "RELEASING_DATE": 'null',
                    "CLOSED_DATE": 'null',
                    "IN_TRANSIT_DATE": 'null',
                    "POD_DATE": 'null',
                    "Rel1 No": "17561",
                    "Rec1 No": 'null',
                    "INVOICE_NO": 'null',
                    "TP_VEHICLE_NO": 'null',
                    "TP_BOOKING": 'null',
                    "TP_CARRIER": 'null',
                    "TP_CONTAINER_NO_1": 'null',
                    "TP_CONTAINER_TYPE_1": 'null',
                    "TP_SEAL_NO_1": 'null',
                    "TP_CONTAINER_NO_2": 'null',
                    "TP_CONTAINER_TYPE_2": 'null',
                    "TP_SEAL_NO_2": 'null',
                    "TP_CONTAINER_NO_3": 'null',
                    "TP_CONTAINER_TYPE_3": 'null',
                    "TP_SEAL_NO_3": 'null',
                    "TP_AIRWAYBILL": 'null',
                    "TP_BILL_OF_LANDING": 'null',
                    "TP_ORIGIN": 'null',
                    "TP_VESSEL": 'null',
                    "TP_PORT_OF_LANDING": 'null',
                    "TP_PORT_DISCHARGE": 'null',
                    "TP_VOYAGE": 'null',
                    "TP_ETD": 'null',
                    "CON_CODE": 'null',
                    "CON_COMPANY": "******",
                    "CON_ADDRESS": "******",
                    "CON_ADDRESS2": "******",
                    "CON_AREA1": "******",
                    "CON_AREA2": "******",
                    "CON_AREA3": "******",
                    "CON_AREA4": "******",
                    "CON_ZONE1": "******",
                    "CON_ZONE2": "******",
                    "CON_REGION1": "******",
                    "CON_REGION2": "******",
                    "CON_COUNTRY": "******",
                    "CON_ZIP": "******",
                    "CON_CONTACT_NAME": "******",
                    "CON_CONTACT_PHONE": "******",
                    "CON_CONTACT_EMAIL": "******",
                    "CON_NOTE": 'null',
                    "ST_CODE": 'null',
                    "ST_COMPANY": "******",
                    "ST_ADDRESS": "******",
                    "ST_ADDRESS2": "******",
                    "ST_AREA1": "******",
                    "ST_AREA2": "******",
                    "ST_AREA3": "******",
                    "ST_AREA4": "******",
                    "ST_ZONE1": "******",
                    "ST_ZONE2": "******",
                    "ST_REGION1": "******",
                    "ST_REGION2": "******",
                    "ST_COUNTRY": "******",
                    "ST_ZIP": "******",
                    "ST_CONTACT_NAME": "******",
                    "ST_CONTACT_PHONE": "******",
                    "ST_CONTACT_EMAIL": "******",
                    "ST_NOTE": 'null',
                    "DEL_CONSIGNMENT": 'null',
                    "DEL_URGENT_ORDER": 'null',
                    "DEL_COD": 'null',
                    "DEL_COD_AMOUNT": 'null',
                    "DELIVERY_TIME_FROM": 'null',
                    "DELIVERY_TIME_TO": 'null',
                    "SHIPPING_INSTRUCTION": 'null',
                    "REMARKS": 'null',
                    "BONDED": False,
                    "TOTAL_PALLET": 0,
                    "STORAGE_CHARGE": True,
                    "IMG_TRUCK_01": 'null',
                    "IMG_TRUCK_02": 'null',
                    "IMG_TRUCK_03": 'null',
                    "IMG_TRUCK_04": 'null',
                    "IMG_TRUCK_05": 'null',
                    "IMG_TRUCK_06": 'null',
                    "IMG_TRUCK_07": 'null',
                    "IMG_TRUCK_08": 'null',
                    "IMG_TRUCK_09": 'null',
                    "IMG_TRUCK_10": 'null',
                    "IMG_TRUCK_THUMB_01": 'null',
                    "IMG_TRUCK_THUMB_02": 'null',
                    "IMG_TRUCK_THUMB_03": 'null',
                    "IMG_TRUCK_THUMB_04": 'null',
                    "IMG_TRUCK_THUMB_05": 'null',
                    "IMG_TRUCK_THUMB_06": 'null',
                    "IMG_TRUCK_THUMB_07": 'null',
                    "IMG_TRUCK_THUMB_08": 'null',
                    "IMG_TRUCK_THUMB_09": 'null',
                    "IMG_TRUCK_THUMB_10": 'null',
                    "IMG_GOODS_01": 'null',
                    "IMG_GOODS_02": 'null',
                    "IMG_GOODS_03": 'null',
                    "IMG_GOODS_04": 'null',
                    "IMG_GOODS_05": 'null',
                    "IMG_GOODS_06": 'null',
                    "IMG_GOODS_07": 'null',
                    "IMG_GOODS_08": 'null',
                    "IMG_GOODS_09": 'null',
                    "IMG_GOODS_10": 'null',
                    "IMG_GOODS_THUMB_01": 'null',
                    "IMG_GOODS_THUMB_02": 'null',
                    "IMG_GOODS_THUMB_03": 'null',
                    "IMG_GOODS_THUMB_04": 'null',
                    "IMG_GOODS_THUMB_05": 'null',
                    "IMG_GOODS_THUMB_06": 'null',
                    "IMG_GOODS_THUMB_07": 'null',
                    "IMG_GOODS_THUMB_08": 'null',
                    "IMG_GOODS_THUMB_09": 'null',
                    "IMG_GOODS_THUMB_10": 'null',
                    "MKP_JOB_BRAND": 'null',
                    "MKP_JOB_NO": 'null',
                    "CREATE_BY": "ft",
                    "MODIFY_BY": "ft",
                    "CREATE_DATE": "2020-11-08T06:36:52.306Z",
                    "MODIFY_DATE": "2020-11-20T08:44:51.457Z",
                    "DELETE_DATE": 'null',
                    "DETAIL": [
                        {
                        "LINE_SEQ": 1,
                        "PRODUCT_TYPE": "FG",
                        "PACK_CODE": "PCS",
                        "PACK_QTY": 1,
                        "PALLET_ID": "AAQ",
                        "CARTON_ID": 'null',
                        "EXPIRY_DATE": 'null',
                        "MANUF_DATE": 'null',
                        "EXP_RELEASE_QTY": 1,
                        "RELEASE_QTY": 1,
                        "ALLOCATED_QTY": 0,
                        "PICKING_QTY": 0,
                        "PICKED_QTY": 0,
                        "PACKED_QTY": 1,
                        "SHIPPED_QTY": 0,
                        "RELEASE_QTY_DIFF": 0,
                        "LOT_NO": 'null',
                        "REMARKS": 'null',
                        "DEBOM": False,
                        "SYS_ID": 'null',
                        "MKP_JOB_DETAIL_NO": 'null',
                        "MKP_DEL_CONSIGNMENT": 'null',
                        "MKP_ST_LABEL": 'null',
                        "MKP_STATUS": 'null',
                        "MKP_INVOICE_NO": 'null',
                        "MKP_PRICE_AFTER_DISCOUNT": 'null',
                        "CREATE_BY": "ft",
                        "MODIFY_BY": "ft",
                        "CREATE_DATE": "2020-11-08T06:36:59.256Z",
                        "MODIFY_DATE": "2020-11-20T08:44:51.442Z",
                        "DELETE_DATE": 'null',
                        "SKU_CODE": "PILLOWB001",
                        "LOCATION_CODE": 'null',
                        "PICK_BY_CODE": "FIFO"
                        }
                    ]
                }
            ]
        }
    return SCPacked_BY_JOB

def create_asn_job():
    ASN = {
                'DATA': [
                    {
                    "<Receive Reference Label-1>": "REC-1611127844",
                    "<Receive Reference Label-2>": "REC-3692523139",
                    "<Receive Reference Label-3>": "REC-8350842351",
                    "<Receive Reference Label-4>": "REC-7576886510",
                    "EXP_RECEIVED_DATE": "2021-11-10T00:00:00+07:00",
                    "TP_VEHICLE_NO": 'null',
                    "TP_CARRIER": 'null',
                    "TP_CONTAINER_NO_1": 'null',
                    "TP_CONTAINER_TYPE_1": 'null',
                    "TP_SEAL_NO_1": 'null',
                    "TP_CONTAINER_NO_2": 'null',
                    "TP_CONTAINER_TYPE_2": 'null',
                    "TP_SEAL_NO_2": 'null',
                    "TP_CONTAINER_NO_3": 'null',
                    "TP_CONTAINER_TYPE_3": 'null',
                    "TP_SEAL_NO_3": 'null',
                    "TP_AIRWAYBILL": 'null',
                    "TP_BILL_OF_LANDING": 'null',
                    "TP_ORIGIN": 'null',
                    "TP_VESSEL": 'null',
                    "TP_PORT_OF_LANDING": 'null',
                    "TP_PORT_DISCHARGE": 'null',
                    "TP_VOYAGE": 'null',
                    "TP_ETA": 'null',
                    "SUP_CODE": 'null',
                    "SUP_COMPANY": 'null',
                    "SUP_ADDRESS": 'null',
                    "SUP_ADDRESS2": 'null',
                    "SUP_AREA1": 'null',
                    "SUP_AREA2": 'null',
                    "SUP_AREA3": 'null',
                    "SUP_AREA4": 'null',
                    "SUP_ZONE1": 'null',
                    "SUP_ZONE2": 'null',
                    "SUP_REGION1": 'null',
                    "SUP_REGION2": 'null',
                    "SUP_COUNTRY": 'null',
                    "SUP_ZIP": 'null',
                    "SUP_CONTACT_NAME": 'null',
                    "SUP_CONTACT_PHONE": 'null',
                    "SUP_CONTACT_EMAIL": 'null',
                    "SUP_NOTE": 'null',
                    "REMARKS": 'null',
                    "<Receive Header User Defined-01>": 'null',
                    "<Receive Header User Defined-02>": 'null',
                    "<Receive Header User Defined-03>": 'null',
                    "<Receive Header User Defined-04>": 'null',
                    "<Receive Header User Defined-05>": 'null',
                    "<Receive Header User Defined-06>": 'null',
                    "<Receive Header User Defined-07>": 'null',
                    "<Receive Header User Defined-08>": 'null',
                    "<Receive Header User Defined-09>": 'null',
                    "<Receive Header User Defined-10>": 'null',
                    "<Receive Header User Defined-11>": 'null',
                    "<Receive Header User Defined-12>": 'null',
                    "<Receive Header User Defined-13>": 'null',
                    "<Receive Header User Defined-14>": 'null',
                    "<Receive Header User Defined-15>": 'null',
                    "DETAIL": [
                        {
                        "SKU_CODE": "123456",
                        "RECEIVED_QTY": 1,
                        "PRODUCT_TYPE": 'null',
                        "PALLET_ID": 'null',
                        "CARTON_ID": 'null',
                        "MANUF_DATE": 'null',
                        "EXPIRY_DATE": 'null',
                        "LENGTH": 'null',
                        "WIDTH": 'null',
                        "HEIGHT": 'null',
                        "LENGTH_UOM": 'null',
                        "VOLUME_UOM": 'null',
                        "GROSS_WEIGHT": 'null',
                        "NET_WEIGHT": 'null',
                        "WEIGHT_UOM": 'null',
                        "PACK_CODE": 'null',
                        "PACK_QTY": 'null',
                        "REMARKS": 'null',
                        "DEBOM": 'null',
                        "LOT_NO": 'null',
                        "PRICE": 'null',
                        "<Receive User Defined-01>": 'null',
                        "<Receive User Defined-02>": 'null',
                        "<Receive User Defined-03>": 'null',
                        "<Receive User Defined-04>": 'null',
                        "<Receive User Defined-05>": 'null',
                        "<Receive User Defined-06>": 'null',
                        "<Receive User Defined-07>": 'null',
                        "<Receive User Defined-08>": 'null',
                        "<Receive User Defined-09>": 'null',
                        "<Receive User Defined-10>": 'null',
                        "<Receive User Defined-11>": 'null',
                        "<Receive User Defined-12>": 'null',
                        "<Receive User Defined-13>": 'null',
                        "<Receive User Defined-14>": 'null',
                        "<Receive User Defined-15>": 'null',
                        "<Receive User Defined-16>": 'null',
                        "<Receive User Defined-17>": 'null',
                        "<Receive User Defined-18>": 'null',
                        "<Receive User Defined-19>": 'null',
                        "<Receive User Defined-20>": 'null',
                        "<Receive User Defined-21>": 'null',
                        "<Receive User Defined-22>": 'null',
                        "<Receive User Defined-23>": 'null',
                        "<Receive User Defined-24>": 'null',
                        "<Receive User Defined-25>": 'null',
                        "<Receive User Defined-26>": 'null',
                        "<Receive User Defined-27>": 'null',
                        "<Receive User Defined-28>": 'null',
                        "<Receive User Defined-29>": 'null',
                        "<Receive User Defined-30>": 'null'
                        }
                    ]
                }
            ]
        }
    return ASN

def update_SKU_Bom():
    BOM = {
        "DATA": [
            {
            "SKU_CODE": "string",
            "CHILDREN": [
                {
                "CHILD_SKU_CODE": "string",
                "QTY": 1
                }
            ]
            }
        ]
        }
    return BOM

def create_or_Update_SKU():
    SKU = {
            'DATA': [
                {
                    'SKU_CODE': 'A101110001',
                    'SKU_DESC': 'null',
                    'SKU_DESC_LOCAL': 'null',
                    'ACTIVE': 'true',
                    'STORAGE_TYPE': 'AMBIENT',
                    'STORAGE_CAT_SERVICE': 'GENERAL',
                    'PRODUCT_TYPE': 'NORMAL',
                    'MATERIAL_TYPE': 'STEEL',
                    'PRODUCT_FAMILY_01': 'null',
                    'PRODUCT_FAMILY_02': 'null',
                    'PRODUCT_FAMILY_03': 'null',
                    'PICK_BY_CODE': 'FIFO',
                    'ABC_CATEGORY': 'null',
                    'ABC_VALUE': '1',
                    'CBM_RATIO': '1',
                    'BOM_SKU': 'false',
                    'DEFAULT_EXPIRY': 'false',
                    'EXPIRY_FROM': 'null',
                    'EXPIRY_DAYS': 'null',
                    'EXPIRY_PERIOD': 'null',
                    'DEFAULT_MANF': 'null',
                    'MANUF_FROM': 'null',
                    'MANUF_DAYS': 'null',
                    'MANUF_PERIOD': 'null',
                    'LAST_CC_DATE': '2020-11-24',
                    'MIN_STOCK_QTY': '0',
                    'MAX_STOCK_QTY': '0',
                    'REQUIRE_SCAN_IN_SERIAL': 'null',
                    'REQUIRE_SCAN_OUT_SERIAL': 'null',
                    'SUSPEND_EDI_UPDATE': 'null',
                    'DEF_SCAN_IN_CONFIG_ID': 1,
                    'SKU_DEFINED_01': 'null',
                    'SKU_DEFINED_02': 'null',
                    'SKU_DEFINED_03': 'null',
                    'SKU_DEFINED_04': 'null',
                    'SKU_DEFINED_05': 'null',
                    'SKU_DEFINED_06': 'null',
                    'SKU_DEFINED_07': 'null',
                    'SKU_DEFINED_08': 'null',
                    'SKU_DEFINED_09': 'null',
                    'SKU_DEFINED_10': 'null',
                    "SKU_IMAGE_1": "",
                    'REMARKS': 'null',
                    'PUTAWAY_BY_CODE': 'null',
                    '1NYBT20RJ4WBXMOJEVA3': "qqq",
                    'DIMENSION': [
                        {
                            'SKU_LEVEL': '1',
                            'PACK_CODE': 'PCS',
                            'PACK_QTY': '3',
                            'DEF_PACK': 'true',
                            'LENGTH': '1.5',
                            'WIDTH': '1.5',
                            'HEIGHT': '1',
                            'LENGTH_UOM': 'CM',
                            'VOLUME': '1',
                            'VOLUME_UOM': 'CBM',
                            'NET_WEIGHT': '1',
                            'GROSS_WEIGHT': '1',
                            'WEIGHT_UOM': 'KG',
                            "PRICE": 1000,
                            "DISCOUNT_BY": 'PERCENT', # PERCENT, VALUE
                            "DISCOUNT_VALUE": 20,
                            "BARCODE": [
                                {
                                    "SKU_REF_CODE": "CCYX",
                                    "SKU_REF_TYPE": "A",
                                    "SKU_REF_BARCODE": "KA1"
                                }
                            ]
                        }
                    ],
                    'BOM': [
                        {
                            "QTY": 19,
                            "SKU_CHILD_CODE": "K113417000",
                        }
                    ]
                }
            ]
        }
    return SKU