

def create_PSO_job():
    CRE_PSO_JOB = {
                "DATA": [
                    {
                    "<Release Reference Label-1>": "REL-8315683480",
                    "<Release Reference Label-2>": "REL-9191904884",
                    "<Release Reference Label-3>": "REL-0303692927",
                    "<Release Reference Label-4>": "REL-3263683094",
                    "PSO_DATE": "2021-11-10T00:00:00+07:00",
                    "REL_PREFIX": '',
                    "TEAM": '',
                    "EXP_RELEASE_DATE": '',
                    "INVOICE_NO": '',
                    "TP_VEHICLE_NO": '',
                    "TP_BOOKING": '',
                    "TP_CARRIER": '',
                    "TP_CONTAINER_NO_1": '',
                    "TP_CONTAINER_TYPE_1": '',
                    "TP_SEAL_NO_1": '',
                    "TP_CONTAINER_NO_2": '',
                    "TP_CONTAINER_TYPE_2": '',
                    "TP_SEAL_NO_2": '',
                    "TP_CONTAINER_NO_3": '',
                    "TP_CONTAINER_TYPE_3": '',
                    "TP_SEAL_NO_3": '',
                    "TP_AIRWAYBILL": '',
                    "TP_BILL_OF_LANDING": '',
                    "TP_ORIGIN": '',
                    "TP_VESSEL": '',
                    "TP_PORT_OF_LANDING": '',
                    "TP_PORT_DISCHARGE": '',
                    "TP_VOYAGE": '',
                    "TP_ETD": '',
                    "CON_CODE": '',
                    "CON_COMPANY": '',
                    "CON_TAX_NO": '',
                    "CON_BRANCH": '',
                    "CON_ADDRESS": '',
                    "CON_ADDRESS2": '',
                    "CON_AREA1": '',
                    "CON_AREA2": '',
                    "CON_AREA3": '',
                    "CON_AREA4": '',
                    "CON_ZONE1": '',
                    "CON_ZONE2": '',
                    "CON_REGION1": '',
                    "CON_REGION2": '',
                    "CON_COUNTRY": '',
                    "CON_ZIP": '',
                    "CON_CONTACT_NAME": '',
                    "CON_CONTACT_PHONE": '',
                    "CON_CONTACT_EMAIL": '',
                    "CON_NOTE": '',
                    "ST_CODE": '',
                    "ST_COMPANY": '',
                    "ST_ADDRESS": '',
                    "ST_ADDRESS2": '',
                    "ST_AREA1": '',
                    "ST_AREA2": '',
                    "ST_AREA3": '',
                    "ST_AREA4": '',
                    "ST_ZONE1": '',
                    "ST_ZONE2": '',
                    "ST_REGION1": '',
                    "ST_REGION2": '',
                    "ST_COUNTRY": '',
                    "ST_ZIP": '',
                    "ST_CONTACT_NAME": '',
                    "ST_CONTACT_PHONE": '',
                    "ST_CONTACT_EMAIL": '',
                    "ST_NOTE": '',
                    "DEL_CONSIGNMENT": '',
                    "DEL_URGENT_ORDER": '',
                    "DEL_COD": '',
                    "DEL_COD_AMOUNT": '',
                    "DELIVERY_TIME_FROM": '',
                    "DELIVERY_TIME_TO": '',
                    "SHIPPING_INSTRUCTION": '',
                    "REMARKS": '',
                    "BONDED": '',
                    "TOTAL_PALLET": '',
                    "STORAGE_CHARGE": '',
                    "<Receive Reference Label-1>": '',
                    "<Receive Reference Label-2>": '',
                    "<Receive Reference Label-3>": '',
                    "<Receive Reference Label-4>": '',
                    "<Release Header User Defined-01>": '',
                    "<Release Header User Defined-02>": '',
                    "<Release Header User Defined-03>": '',
                    "<Release Header User Defined-04>": '',
                    "<Release Header User Defined-05>": '',
                    "<Release Header User Defined-06>": '',
                    "<Release Header User Defined-07>": '',
                    "<Release Header User Defined-08>": '',
                    "<Release Header User Defined-09>": '',
                    "<Release Header User Defined-10>": '',
                    "<Release Header User Defined-11>": '',
                    "<Release Header User Defined-12>": '',
                    "<Release Header User Defined-13>": '',
                    "<Release Header User Defined-14>": '',
                    "<Release Header User Defined-15>": '',
                    "<Receive Header User Defined-01>": '',
                    "<Receive Header User Defined-02>": '',
                    "<Receive Header User Defined-03>": '',
                    "<Receive Header User Defined-04>": '',
                    "<Receive Header User Defined-05>": '',
                    "<Receive Header User Defined-06>": '',
                    "<Receive Header User Defined-07>": '',
                    "<Receive Header User Defined-08>": '',
                    "<Receive Header User Defined-09>": '',
                    "<Receive Header User Defined-10>": '',
                    "<Receive Header User Defined-11>": '',
                    "<Receive Header User Defined-12>": '',
                    "<Receive Header User Defined-13>": '',
                    "<Receive Header User Defined-14>": '',
                    "<Receive Header User Defined-15>": '',
                    "DETAIL": [
                        {
                        "SKU_CODE": "123456",
                        "RELEASE_QTY": 1,
                        "PRODUCT_TYPE": '',
                        "PACK_CODE": '',
                        "PACK_QTY": '',
                        "PALLET_ID": '',
                        "CARTON_ID": '',
                        "EXPIRY_DATE": '',
                        "MANUF_DATE": '',
                        "LOCATION_CODE": '',
                        "LOT_NO": '',
                        "REMARKS": '',
                        "DEBOM": '',
                        "SYS_ID": '',
                        "<Release User Defined-01>": '',
                        "<Release User Defined-02>": '',
                        "<Release User Defined-03>": '',
                        "<Release User Defined-04>": '',
                        "<Release User Defined-05>": '',
                        "<Release User Defined-06>": '',
                        "<Release User Defined-07>": '',
                        "<Release User Defined-08>": '',
                        "<Release User Defined-09>": '',
                        "<Release User Defined-10>": '',
                        "<Release User Defined-11>": '',
                        "<Release User Defined-12>": '',
                        "<Release User Defined-13>": '',
                        "<Release User Defined-14>": '',
                        "<Release User Defined-15>": '',
                        "<Release User Defined-16>": '',
                        "<Release User Defined-17>": '',
                        "<Release User Defined-18>": '',
                        "<Release User Defined-19>": '',
                        "<Release User Defined-20>": '',
                        "<Release User Defined-21>": '',
                        "<Release User Defined-22>": '',
                        "<Release User Defined-23>": '',
                        "<Release User Defined-24>": '',
                        "<Release User Defined-25>": '',
                        "<Release User Defined-26>": '',
                        "<Release User Defined-27>": '',
                        "<Release User Defined-28>": '',
                        "<Release User Defined-29>": '',
                        "<Release User Defined-30>": '',
                        "<Receive User Defined-01>": '',
                        "<Receive User Defined-02>": '',
                        "<Receive User Defined-03>": '',
                        "<Receive User Defined-04>": '',
                        "<Receive User Defined-05>": '',
                        "<Receive User Defined-06>": '',
                        "<Receive User Defined-07>": '',
                        "<Receive User Defined-08>": '',
                        "<Receive User Defined-09>": '',
                        "<Receive User Defined-10>": '',
                        "<Receive User Defined-11>": '',
                        "<Receive User Defined-12>": '',
                        "<Receive User Defined-13>": '',
                        "<Receive User Defined-14>": '',
                        "<Receive User Defined-15>": '',
                        "<Receive User Defined-16>": '',
                        "<Receive User Defined-17>": '',
                        "<Receive User Defined-18>": '',
                        "<Receive User Defined-19>": '',
                        "<Receive User Defined-20>": '',
                        "<Receive User Defined-21>": '',
                        "<Receive User Defined-22>": '',
                        "<Receive User Defined-23>": '',
                        "<Receive User Defined-24>": '',
                        "<Receive User Defined-25>": '',
                        "<Receive User Defined-26>": '',
                        "<Receive User Defined-27>": '',
                        "<Receive User Defined-28>": '',
                        "<Receive User Defined-29>": '',
                        "<Receive User Defined-30>": ''
                        }
                    ]
                }
            ]
        }
    return CRE_PSO_JOB

def create_or_update_partner():
    COU_partner = {
        "DATA": [
            {
            "ACTIVE": True,
            "CODE": "PARTNER01",
            "COMPANY_NAME": "COM01",
            "ADDRESS": '',
            "ADDRESS2": '',
            "AREA1": '',
            "AREA2": '',
            "AREA3": '',
            "AREA4": '',
            "ZONE1": '',
            "ZONE2": '',
            "REGION1": '',
            "REGION2": '',
            "ZIP": '',
            "COUNTRY": '',
            "CONTACT_NAME": '',
            "CONTACT_PHONE": '',
            "CONTACT_EMAIL": '',
            "NOTE": '',
            "REF_TYPE": [
                {
                "TYPE": "P",
                "INFORM_EMAIL": True
                }
            ]
            }
        ]
        }
    return COU_partner

def select_inventory_list():
    SLL = {
                "DATA": [
                    {
                    "COUNT": 1,
                    "PAGE": {
                        "CURRENT": 1,
                        "FIRST": 1,
                        "LAST": 1,
                        "NEXT": 1,
                        "PREV": 1,
                        "SIZE": 10,
                        "TOTAL": 1
                    },
                    "DATA": [
                        {
                        "STORER_CODE": "STR000060",
                        "WH_CODE": "WH01",
                        "SKU_CODE": "PILLOWB001",
                        "SKU_DESC": "PILLOWB001",
                        "SKU_DESC_LOCAL": "หมอน",
                        "PRODUCT_TYPE": "FG",
                        "PALLET_ID": "q",
                        "CARTON_ID": '',
                        "LOT_NO": '',
                        "RECEIVED_DATE": "2021-01-15T03:11:49.392Z",
                        "EXPIRY_DATE": '',
                        "MANUF_DATE": '',
                        "RETURN_DATE": '',
                        "GOOD_CONDITION": "G",
                        "RECEIVE_QTY": 100,
                        "DAMAGED_QTY": 0,
                        "AVAILABLE_QTY": 80,
                        "ON_HAND_QTY": 100,
                        "HOLD_QTY": 20,
                        "HOLD_REASON_CODE": "FREEZ",
                        "CREATE_DATE": "2021-01-15T03:13:06.365Z",
                        "MODIFY_DATE": "2021-10-04T12:23:08.938Z",
                        "PACK_CODE": "PCS",
                        "PACK_QTY": 1,
                        "PRICE": 0,
                        "LENGTH": 1,
                        "WIDTH": 1,
                        "HEIGHT": 1,
                        "UNIT_CUB": 0.1,
                        "WEIGHT_UOM": "KG",
                        "VOLUME_UOM": "CBM",
                        "LENGTH_UOM": "CM",
                        "GROSS_WEIGHT": 1,
                        "NET_WEIGHT": 1,
                        "Rec1 No": '',
                        "RecHU1 No": '',
                        "HREC16": '',
                        "RecU1 No": ''
                        }
                    ]
                }
            ]
        }
    return SLL

def select_goods_receive_by_job():
    SGReceice_BY_JOB = {
            "DATA": [
                {
                "STORER_CODE": "STR000060",
                "WH_CODE": "WH01",
                "RECEIVE_KEY": "0000134340",
                "BATCH_NO": 1,
                "STATUS_CODE": "CLOSED",
                "Rec1 No": "1345",
                "TP_VEHICLE_NO": '',
                "TP_CARRIER": '',
                "TP_CONTAINER_NO_1": '',
                "TP_CONTAINER_TYPE_1": '',
                "TP_SEAL_NO_1": '',
                "TP_CONTAINER_NO_2": '',
                "TP_CONTAINER_TYPE_2": '',
                "TP_SEAL_NO_2": '',
                "TP_CONTAINER_NO_3": '',
                "TP_CONTAINER_TYPE_3": '',
                "TP_SEAL_NO_3": '',
                "TP_AIRWAYBILL": '',
                "TP_BILL_OF_LANDING": '',
                "TP_ORIGIN": '',
                "TP_VESSEL": '',
                "TP_PORT_OF_LANDING": '',
                "TP_PORT_DISCHARGE": '',
                "TP_VOYAGE": '',
                "TP_ETA": '',
                "RECEIVING_START_DATE": '',
                "RECEIVED_DATE": "2020-11-08T06:35:03.570Z",
                "PUTAWAY_START_DATE": '',
                "PUTAWAY_DATE": "2020-11-08T06:36:16.550Z",
                "PUTAWAY_BY": "ft",
                "CLOSED_DATE": "2020-11-08T06:36:40.968Z",
                "SUP_CODE": '',
                "SUP_COMPANY": "******",
                "SUP_ADDRESS": "******",
                "SUP_ADDRESS2": "******",
                "SUP_AREA1": "******",
                "SUP_AREA2": "******",
                "SUP_AREA3": "******",
                "SUP_AREA4": "******",
                "SUP_ZONE1": "******",
                "SUP_ZONE2": "******",
                "SUP_REGION1": "******",
                "SUP_REGION2": "******",
                "SUP_COUNTRY": "******",
                "SUP_ZIP": "******",
                "SUP_CONTACT_NAME": "******",
                "SUP_CONTACT_PHONE": "******",
                "SUP_CONTACT_EMAIL": "******",
                "SUP_NOTE": '',
                "BONDED": False,
                "TOTAL_PALLET": 1,
                "STORAGE_CHARGE": True,
                "RETURN_DATE": '',
                "REMARKS": '',
                "RECEIVED_SIGNED": '',
                "VERIFY_SIGNED": '',
                "RecHU1 No": '',
                "HUSER_DEFINED_16": '',
                "IMG_TRUCK_01": '',
                "IMG_TRUCK_02": '',
                "IMG_TRUCK_03": '',
                "IMG_TRUCK_04": '',
                "IMG_TRUCK_05": '',
                "IMG_TRUCK_06": '',
                "IMG_TRUCK_07": '',
                "IMG_TRUCK_08": '',
                "IMG_TRUCK_09": '',
                "IMG_TRUCK_10": '',
                "IMG_TRUCK_THUMB_01": '',
                "IMG_TRUCK_THUMB_02": '',
                "IMG_TRUCK_THUMB_03": '',
                "IMG_TRUCK_THUMB_04": '',
                "IMG_TRUCK_THUMB_05": '',
                "IMG_TRUCK_THUMB_06": '',
                "IMG_TRUCK_THUMB_07": '',
                "IMG_TRUCK_THUMB_08": '',
                "IMG_TRUCK_THUMB_09": '',
                "IMG_TRUCK_THUMB_10": '',
                "IMG_GOODS_01": '',
                "IMG_GOODS_02": '',
                "IMG_GOODS_03": '',
                "IMG_GOODS_04": '',
                "IMG_GOODS_05": '',
                "IMG_GOODS_06": '',
                "IMG_GOODS_07": '',
                "IMG_GOODS_08": '',
                "IMG_GOODS_09": '',
                "IMG_GOODS_10": '',
                "IMG_GOODS_THUMB_01": '',
                "IMG_GOODS_THUMB_02": '',
                "IMG_GOODS_THUMB_03": '',
                "IMG_GOODS_THUMB_04": '',
                "IMG_GOODS_THUMB_05": '',
                "IMG_GOODS_THUMB_06": '',
                "IMG_GOODS_THUMB_07": '',
                "IMG_GOODS_THUMB_08": '',
                "IMG_GOODS_THUMB_09": '',
                "IMG_GOODS_THUMB_10": '',
                "CREATE_BY": "ft",
                "MODIFY_BY": "ft",
                "CREATE_DATE": "2020-11-08T06:35:05.843Z",
                "MODIFY_DATE": "2020-11-08T06:36:40.969Z",
                "DELETE_DATE": '',
                "DETAIL": [
                    {
                    "SYS_ID": "0000003LCW",
                    "LINE_SEQ": 1,
                    "PRODUCT_TYPE": "FG",
                    "PALLET_ID": "AAQ",
                    "CARTON_ID": '',
                    "MANUF_DATE": '',
                    "EXPIRY_DATE": '',
                    "LENGTH": 1,
                    "WIDTH": 1,
                    "HEIGHT": 1,
                    "LENGTH_UOM": "CM",
                    "UNIT_CUB": 0.000001,
                    "VOLUME_UOM": "CBM",
                    "GROSS_WEIGHT": 1,
                    "NET_WEIGHT": 1,
                    "WEIGHT_UOM": "KG",
                    "GOOD_QTY": 100,
                    "DAMAGED_QTY": 0,
                    "PACK_CODE": "PCS",
                    "PACK_QTY": 1,
                    "CONFIRM_PUTAWAY_QTY": 100,
                    "HOLD": False,
                    "REMARKS": '',
                    "ASN_LINE_SEQ": '',
                    "DEBOM": False,
                    "NON_CONFORMANCE": '',
                    "NON_CONFORMANCE_REMARK": '',
                    "LOT_NO": '',
                    "RecU1 No": '',
                    "PRICE": 0,
                    "CREATE_BY": "ft",
                    "MODIFY_BY": "ft",
                    "CREATE_DATE": "2020-11-08T06:35:15.254Z",
                    "MODIFY_DATE": "2020-11-08T06:36:34.035Z",
                    "DELETE_DATE": '',
                    "SKU_CODE": "PILLOWB001",
                    "LOCATION_CODE": "LOC_WH01",
                    "HOLD_REASON_CODE": ''
                    }
                ]
                }
            ]
            }
    return SGReceice_BY_JOB

def Cancel_DSO():
    CD = {
                "DATA": [
                    {
                "<Release Reference Label-1>": "REL-2735287259",
                "<Release Reference Label-2>": "REL-7563430644",
                "<Release Reference Label-3>": "REL-9045200998",
                "<Release Reference Label-4>": "REL-6992735291"
                }
            ]
        }
    return CD

def Update_Invoice():
    UI = {
                "DATA": [
                    {
                        "<Release Reference Label-1>": "REL-6360249344",
                        "<Release Reference Label-2>": "REL-8065676721",
                        "<Release Reference Label-3>": "REL-1933819033",
                        "<Release Reference Label-4>": "REL-2768953543",
                        "INVOICE_DATA": {
                            "PAYMENT_TYPE": '',
                            "INV_FORMAT_FILE_DESTINATION": '',
                            "INVOICE_DATE": '',
                            "SALE_ORDER_NO": '',
                            "CUSTOMER_PHONE_NUMBER": '',
                            "POSTING_DATE": '',
                            "DUE_DATE": '',
                            "CUSTOMER_PURCHASE_ORDER_REFERENCE": '',
                            "CUSTOMER_ID": '',
                            "CUSTOMER_CODE": '',
                            "CUSTOMER_TAX_ID": '',
                            "CUSTOMER_BRANCH": '',
                            "CUSTOMER_NAME": '',
                            "CUSTOMER_EMAIL": '',
                            "BILL_TO_NAME": '',
                            "BILL_TO_CUSTOMER_ID": '',
                            "BILL_TO_CUSTOMER_NUMBER": '',
                            "BILL_TO_ADDRESS_1": '',
                            "BILL_TO_ADDRESS_2": '',
                            "BILL_TO_CITY": '',
                            "BILL_TO_COUNTRY": '',
                            "BILL_TO_STATE": '',
                            "BILL_TO_POST_CODE": '',
                            "SHIP_TO_CODE": '',
                            "SHIP_TO_NAME": '',
                            "SHIP_TO_CONTACT": '',
                            "SHIP_TO_ADDRESS_1": '',
                            "SHIP_TO_ADDRESS_2": '',
                            "SHIP_TO_CITY": '',
                            "SHIP_TO_COUNTRY": '',
                            "SHIP_TO_STATE": '',
                            "SHIP_TO_POST_CODE": '',
                            "CURRENCY_CODE": '',
                            "PAYMENT_TERM": '',
                            "SALES_PERSON": '',
                            "TAX_CODE": '',
                            "TAX_PERCENT": '',
                            "PRICES_INCLUDE_TAX": '',
                            "REMAINING_AMOUNT": '',
                            "TOTAL_AMOUNT_BEFORE_DISCOUNT": '',
                            "DISCOUNT_AMOUNT": '',
                            "DISCOUNT_APPLIED_BEFORE_TAX": '',
                            "TOTAL_AMOUNT_BEFORE_TAX": '',
                            "TOTAL_TAX_AMOUNT": '',
                            "TOTAL_AMOUNT_INCLUDING_TAX": '',
                            "DEPOSIT_AMOUNT": '',
                            "STATUS": '',
                            "<Release Header User Defined-01>": '',
                            "<Release Header User Defined-02>": '',
                            "<Release Header User Defined-03>": '',
                            "<Release Header User Defined-04>": '',
                            "<Release Header User Defined-05>": '',
                            "<Release Header User Defined-06>": '',
                            "<Release Header User Defined-07>": '',
                            "<Release Header User Defined-08>": '',
                            "<Release Header User Defined-09>": '',
                            "<Release Header User Defined-10>": '',
                            "<Release Header User Defined-11>": '',
                            "<Release Header User Defined-12>": '',
                            "<Release Header User Defined-13>": '',
                            "<Release Header User Defined-14>": '',
                            "<Release Header User Defined-15>": '',
                            "DETAIL": [
                            {
                                "SEQUENCE": '',
                                "ITEM_CODE": '',
                                "ITEM_DESC": '',
                                "PACK_CODE": '',
                                "UNIT_PRICE": '',
                                "QUANTITY": '',
                                "DISCOUNT_AMOUNT": '',
                                "DISCOUNT_PERCENT": '',
                                "DISCOUNT_APPLIED_BEFORE_TAX": '',
                                "AMOUNT_BEFORE_TAX": '',
                                "TAX_CODE": '',
                                "TAX_PERCENT": '',
                                "LINE_AMOUNT_BEFORE_DISCOUNT": '',
                                "INVOICE_DISCOUNT_ALLOCATION": '',
                                "LINE_AMOUNT_BEFORE_TAX": '',
                                "LINE_TAX_AMOUNT": '',
                                "LINE_AMOUNT_INCLUDING_TAX": '',
                                "<Release User Defined-01>": '',
                                "<Release User Defined-02>": '',
                                "<Release User Defined-03>": '',
                                "<Release User Defined-04>": '',
                                "<Release User Defined-05>": '',
                                "<Release User Defined-06>": '',
                                "<Release User Defined-07>": '',
                                "<Release User Defined-08>": '',
                                "<Release User Defined-09>": '',
                                "<Release User Defined-10>": '',
                                "<Release User Defined-11>": '',
                                "<Release User Defined-12>": '',
                                "<Release User Defined-13>": '',
                                "<Release User Defined-14>": '',
                                "<Release User Defined-15>": '',
                                "<Release User Defined-16>": '',
                                "<Release User Defined-17>": '',
                                "<Release User Defined-18>": '',
                                "<Release User Defined-19>": '',
                                "<Release User Defined-20>": '',
                                "<Release User Defined-21>": '',
                                "<Release User Defined-22>": '',
                                "<Release User Defined-23>": '',
                                "<Release User Defined-24>": '',
                                "<Release User Defined-25>": '',
                                "<Release User Defined-26>": '',
                                "<Release User Defined-27>": '',
                                "<Release User Defined-28>": '',
                                "<Release User Defined-29>": '',
                                "<Release User Defined-30>": ''
                            }
                        ]
                    }
                }
            ]
        }
    return UI

def Update_Consignee_and_ShipTo():
    UC_and_SHIPTO = {
                    "DATA":[
                    {
                    "<Release Reference Label-1>": "REL-8714287303",
                    "<Release Reference Label-2>": "REL-7166195423",
                    "<Release Reference Label-3>": "REL-2579928879",
                    "<Release Reference Label-4>": "REL-8804956474",
                    "CON_CODE": '',
                    "CON_COMPANY": '',
                    "CON_TAX_NO": '',
                    "CON_BRANCH": '',
                    "CON_ADDRESS": '',
                    "CON_ADDRESS2": '',
                    "CON_AREA1": '',
                    "CON_AREA2": '',
                    "CON_AREA3": '',
                    "CON_AREA4": '',
                    "CON_ZONE1": '',
                    "CON_ZONE2": '',
                    "CON_REGION1": '',
                    "CON_REGION2": '',
                    "CON_COUNTRY": '',
                    "CON_ZIP": '',
                    "CON_CONTACT_NAME": '',
                    "CON_CONTACT_PHONE": '',
                    "CON_CONTACT_EMAIL": '',
                    "CON_NOTE": '',
                    "ST_CODE": '',
                    "ST_COMPANY": '',
                    "ST_ADDRESS": '',
                    "ST_ADDRESS2": '',
                    "ST_AREA1": '',
                    "ST_AREA2": '',
                    "ST_AREA3": '',
                    "ST_AREA4": '',
                    "ST_ZONE1": '',
                    "ST_ZONE2": '',
                    "ST_REGION1": '',
                    "ST_REGION2": '',
                    "ST_COUNTRY": '',
                    "ST_ZIP": '',
                    "ST_CONTACT_NAME": '',
                    "ST_CONTACT_PHONE": '',
                    "ST_CONTACT_EMAIL": '',
                    "ST_NOTE": ''
                    }
                ]
            }
    return UC_and_SHIPTO

def create_DSO_Job():
    CRE_DSO_JOB = {
                    "DATA": [
                        {
                        "<Release Reference Label-1>": "REL-0682578235",
                        "<Release Reference Label-2>": "REL-2624922914",
                        "<Release Reference Label-3>": "REL-9766789709",
                        "<Release Reference Label-4>": "REL-5069149869",
                        "REL_PREFIX": '',
                        "TEAM": '',
                        "EXP_RELEASE_DATE": '',
                        "INVOICE_NO": '',
                        "TP_VEHICLE_NO": '',
                        "TP_BOOKING": '',
                        "TP_CARRIER": '',
                        "TP_CONTAINER_NO_1": '',
                        "TP_CONTAINER_TYPE_1": '',
                        "TP_SEAL_NO_1": '',
                        "TP_CONTAINER_NO_2": '',
                        "TP_CONTAINER_TYPE_2": '',
                        "TP_SEAL_NO_2": '',
                        "TP_CONTAINER_NO_3": '',
                        "TP_CONTAINER_TYPE_3": '',
                        "TP_SEAL_NO_3": '',
                        "TP_AIRWAYBILL": '',
                        "TP_BILL_OF_LANDING": '',
                        "TP_ORIGIN": '',
                        "TP_VESSEL": '',
                        "TP_PORT_OF_LANDING": '',
                        "TP_PORT_DISCHARGE": '',
                        "TP_VOYAGE": '',
                        "TP_ETD": '',
                        "CON_CODE": '',
                        "CON_COMPANY": '',
                        "CON_TAX_NO": '',
                        "CON_BRANCH": '',
                        "CON_ADDRESS": '',
                        "CON_ADDRESS2": '',
                        "CON_AREA1": '',
                        "CON_AREA2": '',
                        "CON_AREA3": '',
                        "CON_AREA4": '',
                        "CON_ZONE1": '',
                        "CON_ZONE2": '',
                        "CON_REGION1": '',
                        "CON_REGION2": '',
                        "CON_COUNTRY": '',
                        "CON_ZIP": '',
                        "CON_CONTACT_NAME": '',
                        "CON_CONTACT_PHONE": '',
                        "CON_CONTACT_EMAIL": '',
                        "CON_NOTE": '',
                        "ST_CODE": '',
                        "ST_COMPANY": '',
                        "ST_ADDRESS": '',
                        "ST_ADDRESS2": '',
                        "ST_AREA1": '',
                        "ST_AREA2": '',
                        "ST_AREA3": '',
                        "ST_AREA4": '',
                        "ST_ZONE1": '',
                        "ST_ZONE2": '',
                        "ST_REGION1": '',
                        "ST_REGION2": '',
                        "ST_COUNTRY": '',
                        "ST_ZIP": '',
                        "ST_CONTACT_NAME": '',
                        "ST_CONTACT_PHONE": '',
                        "ST_CONTACT_EMAIL": '',
                        "ST_NOTE": '',
                        "DEL_CONSIGNMENT": '',
                        "DEL_URGENT_ORDER": '',
                        "DEL_COD": '',
                        "DEL_COD_AMOUNT": '',
                        "DELIVERY_TIME_FROM": '',
                        "DELIVERY_TIME_TO": '',
                        "SHIPPING_INSTRUCTION": '',
                        "REMARKS": '',
                        "BONDED": '',
                        "TOTAL_PALLET": '',
                        "STORAGE_CHARGE": '',
                        "IMG_TRUCK_01": '',
                        "IMG_TRUCK_02": '',
                        "IMG_TRUCK_03": '',
                        "IMG_TRUCK_04": '',
                        "IMG_TRUCK_05": '',
                        "IMG_TRUCK_06": '',
                        "IMG_TRUCK_07": '',
                        "IMG_TRUCK_08": '',
                        "IMG_TRUCK_09": '',
                        "IMG_TRUCK_10": '',
                        "IMG_GOODS_01": '',
                        "IMG_GOODS_02": '',
                        "IMG_GOODS_03": '',
                        "IMG_GOODS_04": '',
                        "IMG_GOODS_05": '',
                        "IMG_GOODS_06": '',
                        "IMG_GOODS_07": '',
                        "IMG_GOODS_08": '',
                        "IMG_GOODS_09": '',
                        "IMG_GOODS_10": '',
                        "<Release Header User Defined-01>": '',
                        "<Release Header User Defined-02>": '',
                        "<Release Header User Defined-03>": '',
                        "<Release Header User Defined-04>": '',
                        "<Release Header User Defined-05>": '',
                        "<Release Header User Defined-06>": '',
                        "<Release Header User Defined-07>": '',
                        "<Release Header User Defined-08>": '',
                        "<Release Header User Defined-09>": '',
                        "<Release Header User Defined-10>": '',
                        "<Release Header User Defined-11>": '',
                        "<Release Header User Defined-12>": '',
                        "<Release Header User Defined-13>": '',
                        "<Release Header User Defined-14>": '',
                        "<Release Header User Defined-15>": '',
                        "DETAIL": [
                            {
                            "SKU_CODE": "123456",
                            "RELEASE_QTY": 1,
                            "PRODUCT_TYPE": '',
                            "PACK_CODE": '',
                            "PACK_QTY": '',
                            "PALLET_ID": '',
                            "CARTON_ID": '',
                            "EXPIRY_DATE": '',
                            "MANUF_DATE": '',
                            "PICK_BY_CODE": '',
                            "LOCATION_CODE": '',
                            "LOT_NO": '',
                            "REMARKS": '',
                            "DEBOM": '',
                            "SYS_ID": '',
                            "<Release User Defined-01>": '',
                            "<Release User Defined-02>": '',
                            "<Release User Defined-03>": '',
                            "<Release User Defined-04>": '',
                            "<Release User Defined-05>": '',
                            "<Release User Defined-06>": '',
                            "<Release User Defined-07>": '',
                            "<Release User Defined-08>": '',
                            "<Release User Defined-09>": '',
                            "<Release User Defined-10>": '',
                            "<Release User Defined-11>": '',
                            "<Release User Defined-12>": '',
                            "<Release User Defined-13>": '',
                            "<Release User Defined-14>": '',
                            "<Release User Defined-15>": '',
                            "<Release User Defined-16>": '',
                            "<Release User Defined-17>": '',
                            "<Release User Defined-18>": '',
                            "<Release User Defined-19>": '',
                            "<Release User Defined-20>": '',
                            "<Release User Defined-21>": '',
                            "<Release User Defined-22>": '',
                            "<Release User Defined-23>": '',
                            "<Release User Defined-24>": '',
                            "<Release User Defined-25>": '',
                            "<Release User Defined-26>": '',
                            "<Release User Defined-27>": '',
                            "<Release User Defined-28>": '',
                            "<Release User Defined-29>": '',
                            "<Release User Defined-30>": ''
                            }
                        ]
                    }
                ]
            }
    return CRE_DSO_JOB


def select_summary_of_DSO():
    SS_DSO = {
                "DATA" : [
                {
                "JOB_COUNT": 10,
                "JOB_QTY": 200
                }
            ]
        }
    return SS_DSO


def select_summary_of_ASN():
    SS_ASN = {
                "DATA" : [
                {
                "JOB_COUNT": 10,
                "JOB_QTY": 200
                }
            ]
        }
    return SS_ASN

def select_confirm_shipped_by_job():
    SCShipped_BY_JOB = {
                    "DATA": [
                        {
                        "STORER_CODE": "STR000060",
                        "WH_CODE": "WH01",
                        "RELEASE_KEY": "0000019990",
                        "BATCH_NO": 1,
                        "STATUS_CODE": "CLOSED",
                        "REL_PREFIX": '',
                        "TEAM": '',
                        "EXP_RELEASE_DATE": "2020-11-08T06:36:48.759Z",
                        "DRAFT_DATE": "2020-11-08T06:36:52.303Z",
                        "OPENED_DATE": "2020-11-08T06:36:48.759Z",
                        "ALLOCATING_DATE": "2020-11-08T06:37:33.866Z",
                        "ALLOCATED_DATE": "2020-11-08T06:37:46.542Z",
                        "PICKING_DATE": "2020-11-08T06:37:52.042Z",
                        "PICKED_DATE": "2020-11-08T06:37:53.646Z",
                        "PACKING_DATE": "2020-11-08T06:37:53.646Z",
                        "PACKED_DATE": "2020-11-08T06:37:53.646Z",
                        "READY_TO_SHIP_DATE": "2020-11-08T06:37:53.646Z",
                        "RELEASING_DATE": "2020-11-08T06:37:53.646Z",
                        "CLOSED_DATE": "2020-11-08T06:37:53.646Z",
                        "IN_TRANSIT_DATE": '',
                        "POD_DATE": '',
                        "Rel1 No": "17562",
                        "Rec1 No": '',
                        "INVOICE_NO": '',
                        "TP_VEHICLE_NO": '',
                        "TP_BOOKING": '',
                        "TP_CARRIER": '',
                        "TP_CONTAINER_NO_1": '',
                        "TP_CONTAINER_TYPE_1": '',
                        "TP_SEAL_NO_1": '',
                        "TP_CONTAINER_NO_2": '',
                        "TP_CONTAINER_TYPE_2": '',
                        "TP_SEAL_NO_2": '',
                        "TP_CONTAINER_NO_3": '',
                        "TP_CONTAINER_TYPE_3": '',
                        "TP_SEAL_NO_3": '',
                        "TP_AIRWAYBILL": '',
                        "TP_BILL_OF_LANDING": '',
                        "TP_ORIGIN": '',
                        "TP_VESSEL": '',
                        "TP_PORT_OF_LANDING": '',
                        "TP_PORT_DISCHARGE": '',
                        "TP_VOYAGE": '',
                        "TP_ETD": '',
                        "CON_CODE": '',
                        "CON_COMPANY": "******",
                        "CON_ADDRESS": "******",
                        "CON_ADDRESS2": "******",
                        "CON_AREA1": "******",
                        "CON_AREA2": "******",
                        "CON_AREA3": "******",
                        "CON_AREA4": "******",
                        "CON_ZONE1": "******",
                        "CON_ZONE2": "******",
                        "CON_REGION1": "******",
                        "CON_REGION2": "******",
                        "CON_COUNTRY": "******",
                        "CON_ZIP": "******",
                        "CON_CONTACT_NAME": "******",
                        "CON_CONTACT_PHONE": "******",
                        "CON_CONTACT_EMAIL": "******",
                        "CON_NOTE": '',
                        "ST_CODE": '',
                        "ST_COMPANY": "******",
                        "ST_ADDRESS": "******",
                        "ST_ADDRESS2": "******",
                        "ST_AREA1": "******",
                        "ST_AREA2": "******",
                        "ST_AREA3": "******",
                        "ST_AREA4": "******",
                        "ST_ZONE1": "******",
                        "ST_ZONE2": "******",
                        "ST_REGION1": "******",
                        "ST_REGION2": "******",
                        "ST_COUNTRY": "******",
                        "ST_ZIP": "******",
                        "ST_CONTACT_NAME": "******",
                        "ST_CONTACT_PHONE": "******",
                        "ST_CONTACT_EMAIL": "******",
                        "ST_NOTE": '',
                        "DEL_CONSIGNMENT": '',
                        "DEL_URGENT_ORDER": '',
                        "DEL_COD": '',
                        "DEL_COD_AMOUNT": '',
                        "DELIVERY_TIME_FROM": '',
                        "DELIVERY_TIME_TO": '',
                        "SHIPPING_INSTRUCTION": '',
                        "REMARKS": '',
                        "BONDED": False,
                        "TOTAL_PALLET": 0,
                        "STORAGE_CHARGE": True,
                        "IMG_TRUCK_01": '',
                        "IMG_TRUCK_02": '',
                        "IMG_TRUCK_03": '',
                        "IMG_TRUCK_04": '',
                        "IMG_TRUCK_05": '',
                        "IMG_TRUCK_06": '',
                        "IMG_TRUCK_07": '',
                        "IMG_TRUCK_08": '',
                        "IMG_TRUCK_09": '',
                        "IMG_TRUCK_10": '',
                        "IMG_TRUCK_THUMB_01": '',
                        "IMG_TRUCK_THUMB_02": '',
                        "IMG_TRUCK_THUMB_03": '',
                        "IMG_TRUCK_THUMB_04": '',
                        "IMG_TRUCK_THUMB_05": '',
                        "IMG_TRUCK_THUMB_06": '',
                        "IMG_TRUCK_THUMB_07": '',
                        "IMG_TRUCK_THUMB_08": '',
                        "IMG_TRUCK_THUMB_09": '',
                        "IMG_TRUCK_THUMB_10": '',
                        "IMG_GOODS_01": '',
                        "IMG_GOODS_02": '',
                        "IMG_GOODS_03": '',
                        "IMG_GOODS_04": '',
                        "IMG_GOODS_05": '',
                        "IMG_GOODS_06": '',
                        "IMG_GOODS_07": '',
                        "IMG_GOODS_08": '',
                        "IMG_GOODS_09": '',
                        "IMG_GOODS_10": '',
                        "IMG_GOODS_THUMB_01": '',
                        "IMG_GOODS_THUMB_02": '',
                        "IMG_GOODS_THUMB_03": '',
                        "IMG_GOODS_THUMB_04": '',
                        "IMG_GOODS_THUMB_05": '',
                        "IMG_GOODS_THUMB_06": '',
                        "IMG_GOODS_THUMB_07": '',
                        "IMG_GOODS_THUMB_08": '',
                        "IMG_GOODS_THUMB_09": '',
                        "IMG_GOODS_THUMB_10": '',
                        "MKP_JOB_BRAND": '',
                        "MKP_JOB_NO": '',
                        "CREATE_BY": "ft",
                        "MODIFY_BY": "ft",
                        "CREATE_DATE": "2020-11-08T06:36:52.306Z",
                        "MODIFY_DATE": "2020-11-20T08:44:51.457Z",
                        "DELETE_DATE": '',
                        "DETAIL": [
                            {
                            "LINE_SEQ": 1,
                            "PRODUCT_TYPE": "FG",
                            "PACK_CODE": "PCS",
                            "PACK_QTY": 1,
                            "PALLET_ID": "AAQ",
                            "CARTON_ID": '',
                            "EXPIRY_DATE": '',
                            "MANUF_DATE": '',
                            "EXP_RELEASE_QTY": 1,
                            "RELEASE_QTY": 1,
                            "ALLOCATED_QTY": 0,
                            "PICKING_QTY": 0,
                            "PICKED_QTY": 0,
                            "PACKED_QTY": 0,
                            "SHIPPED_QTY": 1,
                            "RELEASE_QTY_DIFF": 0,
                            "LOT_NO": '',
                            "REMARKS": '',
                            "DEBOM": False,
                            "SYS_ID": '',
                            "MKP_JOB_DETAIL_NO": '',
                            "MKP_DEL_CONSIGNMENT": '',
                            "MKP_ST_LABEL": '',
                            "MKP_STATUS": '',
                            "MKP_INVOICE_NO": '',
                            "MKP_PRICE_AFTER_DISCOUNT": '',
                            "CREATE_BY": "ft",
                            "MODIFY_BY": "ft",
                            "CREATE_DATE": "2020-11-08T06:36:59.256Z",
                            "MODIFY_DATE": "2020-11-20T08:44:51.442Z",
                            "DELETE_DATE": '',
                            "SKU_CODE": "PILLOWB001",
                            "LOCATION_CODE": '',
                            "PICK_BY_CODE": "FIFO"
                            }
                        ]
                    }
                ]
            }
    return SCShipped_BY_JOB

def select_confirm_picked_by_job():
    SCPicked_BY_JOB = {
                    "DATA": [
                        {
                        "STORER_CODE": "STR000060",
                        "WH_CODE": "WH01",
                        "RELEASE_KEY": "0000019990",
                        "BATCH_NO": 1,
                        "STATUS_CODE": "PICKED",
                        "REL_PREFIX": '',
                        "TEAM": '',
                        "EXP_RELEASE_DATE": "2020-11-08T06:36:48.759Z",
                        "DRAFT_DATE": "2020-11-08T06:36:52.303Z",
                        "OPENED_DATE": "2020-11-08T06:36:48.759Z",
                        "ALLOCATING_DATE": "2020-11-08T06:37:33.866Z",
                        "ALLOCATED_DATE": "2020-11-08T06:37:46.542Z",
                        "PICKING_DATE": "2020-11-08T06:37:52.042Z",
                        "PICKED_DATE": "2020-11-08T06:37:53.646Z",
                        "PACKING_DATE": '',
                        "PACKED_DATE": '',
                        "READY_TO_SHIP_DATE": '',
                        "RELEASING_DATE": '',
                        "CLOSED_DATE": '',
                        "IN_TRANSIT_DATE": '',
                        "POD_DATE": '',
                        "Rel1 No": "17562",
                        "Rec1 No": '',
                        "INVOICE_NO": '',
                        "TP_VEHICLE_NO": '',
                        "TP_BOOKING": '',
                        "TP_CARRIER": '',
                        "TP_CONTAINER_NO_1": '',
                        "TP_CONTAINER_TYPE_1": '',
                        "TP_SEAL_NO_1": '',
                        "TP_CONTAINER_NO_2": '',
                        "TP_CONTAINER_TYPE_2": '',
                        "TP_SEAL_NO_2": '',
                        "TP_CONTAINER_NO_3": '',
                        "TP_CONTAINER_TYPE_3": '',
                        "TP_SEAL_NO_3": '',
                        "TP_AIRWAYBILL": '',
                        "TP_BILL_OF_LANDING": '',
                        "TP_ORIGIN": '',
                        "TP_VESSEL": '',
                        "TP_PORT_OF_LANDING": '',
                        "TP_PORT_DISCHARGE": '',
                        "TP_VOYAGE": '',
                        "TP_ETD": '',
                        "CON_CODE": '',
                        "CON_COMPANY": "******",
                        "CON_ADDRESS": "******",
                        "CON_ADDRESS2": "******",
                        "CON_AREA1": "******",
                        "CON_AREA2": "******",
                        "CON_AREA3": "******",
                        "CON_AREA4": "******",
                        "CON_ZONE1": "******",
                        "CON_ZONE2": "******",
                        "CON_REGION1": "******",
                        "CON_REGION2": "******",
                        "CON_COUNTRY": "******",
                        "CON_ZIP": "******",
                        "CON_CONTACT_NAME": "******",
                        "CON_CONTACT_PHONE": "******",
                        "CON_CONTACT_EMAIL": "******",
                        "CON_NOTE": '',
                        "ST_CODE": '',
                        "ST_COMPANY": "******",
                        "ST_ADDRESS": "******",
                        "ST_ADDRESS2": "******",
                        "ST_AREA1": "******",
                        "ST_AREA2": "******",
                        "ST_AREA3": "******",
                        "ST_AREA4": "******",
                        "ST_ZONE1": "******",
                        "ST_ZONE2": "******",
                        "ST_REGION1": "******",
                        "ST_REGION2": "******",
                        "ST_COUNTRY": "******",
                        "ST_ZIP": "******",
                        "ST_CONTACT_NAME": "******",
                        "ST_CONTACT_PHONE": "******",
                        "ST_CONTACT_EMAIL": "******",
                        "ST_NOTE": '',
                        "DEL_CONSIGNMENT": '',
                        "DEL_URGENT_ORDER": '',
                        "DEL_COD": '',
                        "DEL_COD_AMOUNT": '',
                        "DELIVERY_TIME_FROM": '',
                        "DELIVERY_TIME_TO": '',
                        "SHIPPING_INSTRUCTION": '',
                        "REMARKS": '',
                        "BONDED": False,
                        "TOTAL_PALLET": 0,
                        "STORAGE_CHARGE": True,
                        "IMG_TRUCK_01": '',
                        "IMG_TRUCK_02": '',
                        "IMG_TRUCK_03": '',
                        "IMG_TRUCK_04": '',
                        "IMG_TRUCK_05": '',
                        "IMG_TRUCK_06": '',
                        "IMG_TRUCK_07": '',
                        "IMG_TRUCK_08": '',
                        "IMG_TRUCK_09": '',
                        "IMG_TRUCK_10": '',
                        "IMG_TRUCK_THUMB_01": '',
                        "IMG_TRUCK_THUMB_02": '',
                        "IMG_TRUCK_THUMB_03": '',
                        "IMG_TRUCK_THUMB_04": '',
                        "IMG_TRUCK_THUMB_05": '',
                        "IMG_TRUCK_THUMB_06": '',
                        "IMG_TRUCK_THUMB_07": '',
                        "IMG_TRUCK_THUMB_08": '',
                        "IMG_TRUCK_THUMB_09": '',
                        "IMG_TRUCK_THUMB_10": '',
                        "IMG_GOODS_01": '',
                        "IMG_GOODS_02": '',
                        "IMG_GOODS_03": '',
                        "IMG_GOODS_04": '',
                        "IMG_GOODS_05": '',
                        "IMG_GOODS_06": '',
                        "IMG_GOODS_07": '',
                        "IMG_GOODS_08": '',
                        "IMG_GOODS_09": '',
                        "IMG_GOODS_10": '',
                        "IMG_GOODS_THUMB_01": '',
                        "IMG_GOODS_THUMB_02": '',
                        "IMG_GOODS_THUMB_03": '',
                        "IMG_GOODS_THUMB_04": '',
                        "IMG_GOODS_THUMB_05": '',
                        "IMG_GOODS_THUMB_06": '',
                        "IMG_GOODS_THUMB_07": '',
                        "IMG_GOODS_THUMB_08": '',
                        "IMG_GOODS_THUMB_09": '',
                        "IMG_GOODS_THUMB_10": '',
                        "MKP_JOB_BRAND": '',
                        "MKP_JOB_NO": '',
                        "CREATE_BY": "ft",
                        "MODIFY_BY": "ft",
                        "CREATE_DATE": "2020-11-08T06:36:52.306Z",
                        "MODIFY_DATE": "2020-11-20T08:44:51.457Z",
                        "DELETE_DATE": '',
                        "DETAIL": [
                            {
                            "LINE_SEQ": 1,
                            "PRODUCT_TYPE": "FG",
                            "PACK_CODE": "PCS",
                            "PACK_QTY": 1,
                            "PALLET_ID": "AAQ",
                            "CARTON_ID": '',
                            "EXPIRY_DATE": '',
                            "MANUF_DATE": '',
                            "EXP_RELEASE_QTY": 1,
                            "RELEASE_QTY": 1,
                            "ALLOCATED_QTY": 0,
                            "PICKING_QTY": 0,
                            "PICKED_QTY": 0,
                            "PACKED_QTY": 1,
                            "SHIPPED_QTY": 0,
                            "RELEASE_QTY_DIFF": 0,
                            "LOT_NO": '',
                            "REMARKS": '',
                            "DEBOM": False,
                            "SYS_ID": '',
                            "MKP_JOB_DETAIL_NO": '',
                            "MKP_DEL_CONSIGNMENT": '',
                            "MKP_ST_LABEL": '',
                            "MKP_STATUS": '',
                            "MKP_INVOICE_NO": '',
                            "MKP_PRICE_AFTER_DISCOUNT": '',
                            "CREATE_BY": "ft",
                            "MODIFY_BY": "ft",
                            "CREATE_DATE": "2020-11-08T06:36:59.256Z",
                            "MODIFY_DATE": "2020-11-20T08:44:51.442Z",
                            "DELETE_DATE": '',
                            "SKU_CODE": "PILLOWB001",
                            "LOCATION_CODE": '',
                            "PICK_BY_CODE": "FIFO"
                            }
                        ]
                    }
                ]
            }
    return SCPicked_BY_JOB

def select_confirm_packed_by_job():
    SCPacked_BY_JOB = {
                "DATA": [
                    {
                    "STORER_CODE": "STR000060",
                    "WH_CODE": "WH01",
                    "RELEASE_KEY": "0000019989",
                    "BATCH_NO": 1,
                    "STATUS_CODE": "PACKED",
                    "REL_PREFIX": '',
                    "TEAM": '',
                    "EXP_RELEASE_DATE": "2020-11-08T06:36:48.759Z",
                    "DRAFT_DATE": "2020-11-08T06:36:52.303Z",
                    "OPENED_DATE": "2020-11-08T06:36:48.759Z",
                    "ALLOCATING_DATE": "2020-11-08T06:37:33.866Z",
                    "ALLOCATED_DATE": "2020-11-08T06:37:46.542Z",
                    "PICKING_DATE": "2020-11-08T06:37:52.042Z",
                    "PICKED_DATE": "2020-11-08T06:37:53.646Z",
                    "PACKING_DATE": "2020-11-08T06:55:13.989Z",
                    "PACKED_DATE": "2020-11-08T06:55:13.989Z",
                    "READY_TO_SHIP_DATE": '',
                    "RELEASING_DATE": '',
                    "CLOSED_DATE": '',
                    "IN_TRANSIT_DATE": '',
                    "POD_DATE": '',
                    "Rel1 No": "17561",
                    "Rec1 No": '',
                    "INVOICE_NO": '',
                    "TP_VEHICLE_NO": '',
                    "TP_BOOKING": '',
                    "TP_CARRIER": '',
                    "TP_CONTAINER_NO_1": '',
                    "TP_CONTAINER_TYPE_1": '',
                    "TP_SEAL_NO_1": '',
                    "TP_CONTAINER_NO_2": '',
                    "TP_CONTAINER_TYPE_2": '',
                    "TP_SEAL_NO_2": '',
                    "TP_CONTAINER_NO_3": '',
                    "TP_CONTAINER_TYPE_3": '',
                    "TP_SEAL_NO_3": '',
                    "TP_AIRWAYBILL": '',
                    "TP_BILL_OF_LANDING": '',
                    "TP_ORIGIN": '',
                    "TP_VESSEL": '',
                    "TP_PORT_OF_LANDING": '',
                    "TP_PORT_DISCHARGE": '',
                    "TP_VOYAGE": '',
                    "TP_ETD": '',
                    "CON_CODE": '',
                    "CON_COMPANY": "******",
                    "CON_ADDRESS": "******",
                    "CON_ADDRESS2": "******",
                    "CON_AREA1": "******",
                    "CON_AREA2": "******",
                    "CON_AREA3": "******",
                    "CON_AREA4": "******",
                    "CON_ZONE1": "******",
                    "CON_ZONE2": "******",
                    "CON_REGION1": "******",
                    "CON_REGION2": "******",
                    "CON_COUNTRY": "******",
                    "CON_ZIP": "******",
                    "CON_CONTACT_NAME": "******",
                    "CON_CONTACT_PHONE": "******",
                    "CON_CONTACT_EMAIL": "******",
                    "CON_NOTE": '',
                    "ST_CODE": '',
                    "ST_COMPANY": "******",
                    "ST_ADDRESS": "******",
                    "ST_ADDRESS2": "******",
                    "ST_AREA1": "******",
                    "ST_AREA2": "******",
                    "ST_AREA3": "******",
                    "ST_AREA4": "******",
                    "ST_ZONE1": "******",
                    "ST_ZONE2": "******",
                    "ST_REGION1": "******",
                    "ST_REGION2": "******",
                    "ST_COUNTRY": "******",
                    "ST_ZIP": "******",
                    "ST_CONTACT_NAME": "******",
                    "ST_CONTACT_PHONE": "******",
                    "ST_CONTACT_EMAIL": "******",
                    "ST_NOTE": '',
                    "DEL_CONSIGNMENT": '',
                    "DEL_URGENT_ORDER": '',
                    "DEL_COD": '',
                    "DEL_COD_AMOUNT": '',
                    "DELIVERY_TIME_FROM": '',
                    "DELIVERY_TIME_TO": '',
                    "SHIPPING_INSTRUCTION": '',
                    "REMARKS": '',
                    "BONDED": False,
                    "TOTAL_PALLET": 0,
                    "STORAGE_CHARGE": True,
                    "IMG_TRUCK_01": '',
                    "IMG_TRUCK_02": '',
                    "IMG_TRUCK_03": '',
                    "IMG_TRUCK_04": '',
                    "IMG_TRUCK_05": '',
                    "IMG_TRUCK_06": '',
                    "IMG_TRUCK_07": '',
                    "IMG_TRUCK_08": '',
                    "IMG_TRUCK_09": '',
                    "IMG_TRUCK_10": '',
                    "IMG_TRUCK_THUMB_01": '',
                    "IMG_TRUCK_THUMB_02": '',
                    "IMG_TRUCK_THUMB_03": '',
                    "IMG_TRUCK_THUMB_04": '',
                    "IMG_TRUCK_THUMB_05": '',
                    "IMG_TRUCK_THUMB_06": '',
                    "IMG_TRUCK_THUMB_07": '',
                    "IMG_TRUCK_THUMB_08": '',
                    "IMG_TRUCK_THUMB_09": '',
                    "IMG_TRUCK_THUMB_10": '',
                    "IMG_GOODS_01": '',
                    "IMG_GOODS_02": '',
                    "IMG_GOODS_03": '',
                    "IMG_GOODS_04": '',
                    "IMG_GOODS_05": '',
                    "IMG_GOODS_06": '',
                    "IMG_GOODS_07": '',
                    "IMG_GOODS_08": '',
                    "IMG_GOODS_09": '',
                    "IMG_GOODS_10": '',
                    "IMG_GOODS_THUMB_01": '',
                    "IMG_GOODS_THUMB_02": '',
                    "IMG_GOODS_THUMB_03": '',
                    "IMG_GOODS_THUMB_04": '',
                    "IMG_GOODS_THUMB_05": '',
                    "IMG_GOODS_THUMB_06": '',
                    "IMG_GOODS_THUMB_07": '',
                    "IMG_GOODS_THUMB_08": '',
                    "IMG_GOODS_THUMB_09": '',
                    "IMG_GOODS_THUMB_10": '',
                    "MKP_JOB_BRAND": '',
                    "MKP_JOB_NO": '',
                    "CREATE_BY": "ft",
                    "MODIFY_BY": "ft",
                    "CREATE_DATE": "2020-11-08T06:36:52.306Z",
                    "MODIFY_DATE": "2020-11-20T08:44:51.457Z",
                    "DELETE_DATE": '',
                    "DETAIL": [
                        {
                        "LINE_SEQ": 1,
                        "PRODUCT_TYPE": "FG",
                        "PACK_CODE": "PCS",
                        "PACK_QTY": 1,
                        "PALLET_ID": "AAQ",
                        "CARTON_ID": '',
                        "EXPIRY_DATE": '',
                        "MANUF_DATE": '',
                        "EXP_RELEASE_QTY": 1,
                        "RELEASE_QTY": 1,
                        "ALLOCATED_QTY": 0,
                        "PICKING_QTY": 0,
                        "PICKED_QTY": 0,
                        "PACKED_QTY": 1,
                        "SHIPPED_QTY": 0,
                        "RELEASE_QTY_DIFF": 0,
                        "LOT_NO": '',
                        "REMARKS": '',
                        "DEBOM": False,
                        "SYS_ID": '',
                        "MKP_JOB_DETAIL_NO": '',
                        "MKP_DEL_CONSIGNMENT": '',
                        "MKP_ST_LABEL": '',
                        "MKP_STATUS": '',
                        "MKP_INVOICE_NO": '',
                        "MKP_PRICE_AFTER_DISCOUNT": '',
                        "CREATE_BY": "ft",
                        "MODIFY_BY": "ft",
                        "CREATE_DATE": "2020-11-08T06:36:59.256Z",
                        "MODIFY_DATE": "2020-11-20T08:44:51.442Z",
                        "DELETE_DATE": '',
                        "SKU_CODE": "PILLOWB001",
                        "LOCATION_CODE": '',
                        "PICK_BY_CODE": "FIFO"
                        }
                    ]
                }
            ]
        }
    return SCPacked_BY_JOB

def create_asn_job():
    ASN = {
                'DATA': [
                    {
                    "<Receive Reference Label-1>": "REC-1611127844",
                    "<Receive Reference Label-2>": "REC-3692523139",
                    "<Receive Reference Label-3>": "REC-8350842351",
                    "<Receive Reference Label-4>": "REC-7576886510",
                    "EXP_RECEIVED_DATE": "2021-11-10T00:00:00+07:00",
                    "TP_VEHICLE_NO": '',
                    "TP_CARRIER": '',
                    "TP_CONTAINER_NO_1": '',
                    "TP_CONTAINER_TYPE_1": '',
                    "TP_SEAL_NO_1": '',
                    "TP_CONTAINER_NO_2": '',
                    "TP_CONTAINER_TYPE_2": '',
                    "TP_SEAL_NO_2": '',
                    "TP_CONTAINER_NO_3": '',
                    "TP_CONTAINER_TYPE_3": '',
                    "TP_SEAL_NO_3": '',
                    "TP_AIRWAYBILL": '',
                    "TP_BILL_OF_LANDING": '',
                    "TP_ORIGIN": '',
                    "TP_VESSEL": '',
                    "TP_PORT_OF_LANDING": '',
                    "TP_PORT_DISCHARGE": '',
                    "TP_VOYAGE": '',
                    "TP_ETA": '',
                    "SUP_CODE": '',
                    "SUP_COMPANY": '',
                    "SUP_ADDRESS": '',
                    "SUP_ADDRESS2": '',
                    "SUP_AREA1": '',
                    "SUP_AREA2": '',
                    "SUP_AREA3": '',
                    "SUP_AREA4": '',
                    "SUP_ZONE1": '',
                    "SUP_ZONE2": '',
                    "SUP_REGION1": '',
                    "SUP_REGION2": '',
                    "SUP_COUNTRY": '',
                    "SUP_ZIP": '',
                    "SUP_CONTACT_NAME": '',
                    "SUP_CONTACT_PHONE": '',
                    "SUP_CONTACT_EMAIL": '',
                    "SUP_NOTE": '',
                    "REMARKS": '',
                    "<Receive Header User Defined-01>": '',
                    "<Receive Header User Defined-02>": '',
                    "<Receive Header User Defined-03>": '',
                    "<Receive Header User Defined-04>": '',
                    "<Receive Header User Defined-05>": '',
                    "<Receive Header User Defined-06>": '',
                    "<Receive Header User Defined-07>": '',
                    "<Receive Header User Defined-08>": '',
                    "<Receive Header User Defined-09>": '',
                    "<Receive Header User Defined-10>": '',
                    "<Receive Header User Defined-11>": '',
                    "<Receive Header User Defined-12>": '',
                    "<Receive Header User Defined-13>": '',
                    "<Receive Header User Defined-14>": '',
                    "<Receive Header User Defined-15>": '',
                    "DETAIL": [
                        {
                        "SKU_CODE": "123456",
                        "RECEIVED_QTY": 1,
                        "PRODUCT_TYPE": '',
                        "PALLET_ID": '',
                        "CARTON_ID": '',
                        "MANUF_DATE": '',
                        "EXPIRY_DATE": '',
                        "LENGTH": '',
                        "WIDTH": '',
                        "HEIGHT": '',
                        "LENGTH_UOM": '',
                        "VOLUME_UOM": '',
                        "GROSS_WEIGHT": '',
                        "NET_WEIGHT": '',
                        "WEIGHT_UOM": '',
                        "PACK_CODE": '',
                        "PACK_QTY": '',
                        "REMARKS": '',
                        "DEBOM": '',
                        "LOT_NO": '',
                        "PRICE": '',
                        "<Receive User Defined-01>": '',
                        "<Receive User Defined-02>": '',
                        "<Receive User Defined-03>": '',
                        "<Receive User Defined-04>": '',
                        "<Receive User Defined-05>": '',
                        "<Receive User Defined-06>": '',
                        "<Receive User Defined-07>": '',
                        "<Receive User Defined-08>": '',
                        "<Receive User Defined-09>": '',
                        "<Receive User Defined-10>": '',
                        "<Receive User Defined-11>": '',
                        "<Receive User Defined-12>": '',
                        "<Receive User Defined-13>": '',
                        "<Receive User Defined-14>": '',
                        "<Receive User Defined-15>": '',
                        "<Receive User Defined-16>": '',
                        "<Receive User Defined-17>": '',
                        "<Receive User Defined-18>": '',
                        "<Receive User Defined-19>": '',
                        "<Receive User Defined-20>": '',
                        "<Receive User Defined-21>": '',
                        "<Receive User Defined-22>": '',
                        "<Receive User Defined-23>": '',
                        "<Receive User Defined-24>": '',
                        "<Receive User Defined-25>": '',
                        "<Receive User Defined-26>": '',
                        "<Receive User Defined-27>": '',
                        "<Receive User Defined-28>": '',
                        "<Receive User Defined-29>": '',
                        "<Receive User Defined-30>": ''
                        }
                    ]
                }
            ]
        }
    return ASN

def update_SKU_Bom():
    BOM = {
        "DATA": [
            {
            "SKU_CODE": "string",
            "CHILDREN": [
                {
                "CHILD_SKU_CODE": "string",
                "QTY": 1
                }
            ]
            }
        ]
        }
    return BOM

def create_or_Update_SKU():
    SKU = {
        "DATA": [
            {
            "SKU_CODE": "123456",
            "ACTIVE": True,
            "STORAGE_TYPE": "AMBIENT",
            "STORAGE_CAT_SERVICE": "GENERAL",
            "PRODUCT_TYPE": "NORMAL",
            "PICK_BY_CODE": "FIFO",
            "CBM_RATIO": 0,
            "BOM_SKU": False,
            "DEFAULT_EXPIRY": True,
            "SKU_DESC": '',
            "SKU_DESC_LOCAL": '',
            "MATERIAL_TYPE": '',
            "PRODUCT_FAMILY_01": '',
            "PRODUCT_FAMILY_02": '',
            "PRODUCT_FAMILY_03": '',
            "ABC_VALUE": '',
            "ABC_TRANSACTION": '',
            "EXPIRY_FROM": '',
            "EXPIRY_DAYS": '',
            "EXPIRY_PERIOD": '',
            "DEFAULT_MANF": '',
            "MANUF_FROM": '',
            "MANUF_DAYS": '',
            "MANUF_PERIOD": '',
            "LAST_CC_DATE": '',
            "MIN_STOCK_QTY": '',
            "MIN_REORDER_QTY": '',
            "MAX_STOCK_QTY": '',
            "MIN_SHELF_LIFE": '',
            "DAY_PREPARE_SHIP": '',
            "REQUIRE_SCAN_IN_SERIAL": '',
            "REQUIRE_SCAN_OUT_SERIAL": '',
            "SKU_IMAGE_1": '',
            "SKU_IMAGE_2": '',
            "SKU_IMAGE_3": '',
            "SKU_IMAGE_4": '',
            "SKU_IMAGE_5": '',
            "SKU_IMAGE_6": '',
            "SKU_IMAGE_7": '',
            "SKU_IMAGE_8": '',
            "SKU_IMAGE_9": '',
            "SKU_IMAGE_10": '',
            "REMARKS": '',
            "COLOUR": '',
            "STYLE": '',
            "SKU_ADS_DETAIL": '',
            "RECEIVE_MIN_DAYS": '',
            "<SKU User Defined-01>": '',
            "<SKU User Defined-02>": '',
            "<SKU User Defined-03>": '',
            "<SKU User Defined-04>": '',
            "<SKU User Defined-05>": '',
            "<SKU User Defined-06>": '',
            "<SKU User Defined-07>": '',
            "<SKU User Defined-08>": '',
            "<SKU User Defined-09>": '',
            "<SKU User Defined-10>": '',
            "DIMENSION": [
                {
                "SKU_LEVEL": 1,
                "PACK_CODE": "PCS",
                "PACK_QTY": 1,
                "DEF_PACK": True,
                "LENGTH": 1,
                "WIDTH": 1,
                "HEIGHT": 1,
                "LENGTH_UOM": "CM",
                "VOLUME": 1,
                "VOLUME_UOM": "CBM",
                "NET_WEIGHT": 1,
                "GROSS_WEIGHT": 1,
                "WEIGHT_UOM": "TON",
                "DEF_PACK_CAL": '',
                "DEF_MKP": '',
                "PRICE": '',
                "DISCOUNT_BY": '',
                "DISCOUNT_VALUE": '',
                "BUBBLE_RATIO": '',
                "SUG_PACKAGE_SIZE": '',
                "BARCODE": [
                    {
                    "SKU_REF_TYPE": "M",
                    "SKU_REF_BARCODE": "CODE123456",
                    "SKU_REF_CODE": '',
                    "GS1_EXTENSION": ''
                    }
                ]
                }
            ],
            "BOM": [
                {
                "SKU_CHILD_CODE": "CH123456",
                "QTY": 1
                }
            ]
            }
        ]
        }
    return SKU